---
-- @Liquipedia
-- wiki=commons
-- page=Module:Flags/MasterData
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

-- There are four tables:
--   data (contains flag images. Should have one entry per image)
--   twoLetter (two-letter country codes as per ISO 3166-1 alpha-2)
--   threeLetter (three-letter country codes)
--   aliases (redirects to the appropriate index in the data table)

-- This table includes:
--   ISO 3166-1 alpha-2
--   ISO 3166-1 alpha-2 User-assigned Code Elements
--   ISO 3166-1 alpha-2 Exceptional Reservations
--   ISO 3166-1 alpha-2 Traditional Reservations
--   ISO 3166-2:GB
--   Other
local data = {
	-- ISO 3166-1 alpha-2
	['afghanistan'] = {
		flag = 'File:af_hd.png',
		localised = 'Afghan',
		name = 'Afghanistan',
	},
	['albania'] = {
		flag = 'File:al_hd.png',
		localised = 'Albanian',
		name = 'Albania',
	},
	['algeria'] = {
		flag = 'File:dz_hd.png',
		localised = 'Algerian',
		name = 'Algeria',
	},
	['americansamoa'] = {
		flag = 'File:as_hd.png',
		localised = 'American Samoan',
		name = 'American Samoa',
	},
	['andorra'] = {
		flag = 'File:ad_hd.png',
		localised = 'Andorran',
		name = 'Andorra',
	},
	['angola'] = {
		flag = 'File:ao_hd.png',
		localised = 'Angolan',
		name = 'Angola',
	},
	['anguilla'] = {
		flag = 'File:ai_hd.png',
		localised = 'Anguillan',
		name = 'Anguilla',
	},
	['antarctica'] = {
		flag = 'File:aq_hd.png',
		localised = 'Antarctic',
		name = 'Antarctica',
	},
	['antiguaandbarbuda'] = {
		flag = 'File:ag_hd.png',
		localised = 'Antigua and Barbuda',
		name = 'Antigua and Barbuda',
	},
	['argentina'] = {
		flag = 'File:ar_hd.png',
		localised = 'Argentine',
		name = 'Argentina',
	},
	['armenia'] = {
		flag = 'File:am_hd.png',
		localised = 'Armenian',
		name = 'Armenia',
	},
	['aruba'] = {
		flag = 'File:aw_hd.png',
		localised = 'Aruban',
		name = 'Aruba',
	},
	['ascensionisland'] = {
		flag = 'File:ac_hd.png',
		localised = 'Saint Helenian',
		name = 'Ascension Island',
	},
	['australia'] = {
		flag = 'File:au_hd.png',
		localised = 'Australian',
		name = 'Australia',
	},
	['austria'] = {
		flag = 'File:at_hd.png',
		localised = 'Austrian',
		name = 'Austria',
	},
	['azerbaijan'] = {
		flag = 'File:az_hd.png',
		localised = 'Azerbaijani',
		name = 'Azerbaijan',
	},
	['bahamas'] = {
		flag = 'File:bs_hd.png',
		localised = 'Bahamian',
		name = 'Bahamas',
	},
	['bahrain'] = {
		flag = 'File:bh_hd.png',
		localised = 'Bahraini',
		name = 'Bahrain',
	},
	['bangladesh'] = {
		flag = 'File:bd_hd.png',
		localised = 'Bangladeshi',
		name = 'Bangladesh',
	},
	['barbados'] = {
		flag = 'File:bb_hd.png',
		localised = 'Barbadian',
		name = 'Barbados',
	},
	['belarus'] = {
		flag = 'File:by_hd.png',
		localised = 'Belarusian',
		name = 'Belarus',
	},
	['belgium'] = {
		flag = 'File:be_hd.png',
		localised = 'Belgian',
		name = 'Belgium',
	},
	['belize'] = {
		flag = 'File:bz_hd.png',
		localised = 'Belizean',
		name = 'Belize',
	},
	['benin'] = {
		flag = 'File:bj_hd.png',
		localised = 'Beninese',
		name = 'Benin',
	},
	['bermuda'] = {
		flag = 'File:bm_hd.png',
		localised = 'Bermudian',
		name = 'Bermuda',
	},
	['bhutan'] = {
		flag = 'File:bt_hd.png',
		localised = 'Bhutanese',
		name = 'Bhutan',
	},
	['bolivia'] = {
		flag = 'File:bo_hd.png',
		localised = 'Bolivian',
		name = 'Bolivia',
	},
	['bonaire,sinteustatiusandsaba'] = {
		flag = 'File:bq_hd.png',
		localised = 'Bonairean',
		name = 'Bonaire, Sint Eustatius and Saba',
	},
	['bosniaandherzegovina'] = {
		flag = 'File:ba_hd.png',
		localised = 'Bosnian',
		name = 'Bosnia and Herzegovina',
	},
	['botswana'] = {
		flag = 'File:bw_hd.png',
		localised = 'Botswanan',
		name = 'Botswana',
	},
	['bouvetisland'] = {
		flag = 'File:bv_hd.png',
		localised = 'Bouvet Islander',
		name = 'Bouvet Island',
	},
	['brazil'] = {
		flag = 'File:br_hd.png',
		localised = 'Brazilian',
		name = 'Brazil',
	},
	['britishindianoceanterritory'] = {
		flag = 'File:io_hd.png',
		localised = 'British Indian Ocean Territory',
		name = 'British Indian Ocean Territory',
	},
	['brunei'] = {
		flag = 'File:bn_hd.png',
		localised = 'Bruneian',
		name = 'Brunei',
	},
	['bulgaria'] = {
		flag = 'File:bg_hd.png',
		localised = 'Bulgarian',
		name = 'Bulgaria',
	},
	['burkinafaso'] = {
		flag = 'File:bf_hd.png',
		localised = 'Burkinabé',
		name = 'Burkina Faso',
	},
	['burundi'] = {
		flag = 'File:bi_hd.png',
		localised = 'Burundian',
		name = 'Burundi',
	},
	['caboverde'] = {
		flag = 'File:cv_hd.png',
		localised = 'Cape Verdean',
		name = 'Cabo Verde',
	},
	['cambodia'] = {
		flag = 'File:kh_hd.png',
		localised = 'Cambodian',
		name = 'Cambodia',
	},
	['cameroon'] = {
		flag = 'File:cm_hd.png',
		localised = 'Cameroonian',
		name = 'Cameroon',
	},
	['canada'] = {
		flag = 'File:ca_hd.png',
		localised = 'Canadian',
		name = 'Canada',
	},
	['caymanislands'] = {
		flag = 'File:ky_hd.png',
		localised = 'Caymanian',
		name = 'Cayman Islands',
	},
	['centralafricanrepublic'] = {
		flag = 'File:cf_hd.png',
		localised = 'Central African',
		name = 'Central African Republic',
	},
	['chad'] = {
		flag = 'File:td_hd.png',
		localised = 'Chadian',
		name = 'Chad',
	},
	['chile'] = {
		flag = 'File:cl_hd.png',
		localised = 'Chilean',
		name = 'Chile',
	},
	['china'] = {
		flag = 'File:cn_hd.png',
		localised = 'Chinese',
		name = 'China',
	},
	['christmasisland'] = {
		flag = 'File:cx_hd.png',
		localised = 'Christmas Islander',
		name = 'Christmas Island',
	},
	['cocos(keeling)islands'] = {
		flag = 'File:cc_hd.png',
		localised = 'Cocos Islander',
		name = 'Cocos (Keeling) Islands',
	},
	['colombia'] = {
		flag = 'File:co_hd.png',
		localised = 'Colombian',
		name = 'Colombia',
	},
	['comoros'] = {
		flag = 'File:km_hd.png',
		localised = 'Comorian',
		name = 'Comoros',
	},
	['congo'] = {
		flag = 'File:cg_hd.png',
		localised = 'Congolese',
		name = 'Congo',
	},
	['congo,democraticrepublicofthe'] = {
		flag = 'File:cd_hd.png',
		localised = 'Congolese',
		name = 'Democratic Republic of the Congo',
	},
	['cookislands'] = {
		flag = 'File:ck_hd.png',
		localised = 'Cook Islander',
		name = 'Cook Islands',
	},
	['costarica'] = {
		flag = 'File:cr_hd.png',
		localised = 'Costa Rican',
		name = 'Costa Rica',
	},
	['croatia'] = {
		flag = 'File:hr_hd.png',
		localised = 'Croatian',
		name = 'Croatia',
	},
	['cuba'] = {
		flag = 'File:cu_hd.png',
		localised = 'Cuban',
		name = 'Cuba',
	},
	['curaçao'] = {
		flag = 'File:cw_hd.png',
		localised = 'Curaçaoan',
		name = 'Curaçao',
	},
	['cyprus'] = {
		flag = 'File:cy_hd.png',
		localised = 'Cypriot',
		name = 'Cyprus',
	},
	['czechia'] = {
		flag = 'File:cz_hd.png',
		localised = 'Czech',
		name = 'Czechia',
	},
	['côted\'ivoire'] = {
		flag = 'File:ci_hd.png',
		localised = 'Ivorian',
		name = 'Côte d\'Ivoire',
	},
	['denmark'] = {
		flag = 'File:dk_hd.png',
		localised = 'Danish',
		name = 'Denmark',
	},
	['djibouti'] = {
		flag = 'File:dj_hd.png',
		localised = 'Djiboutian',
		name = 'Djibouti',
	},
	['dominica'] = {
		flag = 'File:dm_hd.png',
		localised = 'Dominica',
		name = 'Dominica',
	},
	['dominicanrepublic'] = {
		flag = 'File:do_hd.png',
		localised = 'Dominican',
		name = 'Dominican Republic',
	},
	['ecuador'] = {
		flag = 'File:ec_hd.png',
		localised = 'Ecuadorian',
		name = 'Ecuador',
	},
	['egypt'] = {
		flag = 'File:eg_hd.png',
		localised = 'Egyptian',
		name = 'Egypt',
	},
	['elsalvador'] = {
		flag = 'File:sv_hd.png',
		localised = 'Salvadoran',
		name = 'El Salvador',
	},
	['equatorialguinea'] = {
		flag = 'File:gq_hd.png',
		localised = 'Equatoguinean',
		name = 'Equatorial Guinea',
	},
	['eritrea'] = {
		flag = 'File:er_hd.png',
		localised = 'Eritrean',
		name = 'Eritrea',
	},
	['estonia'] = {
		flag = 'File:ee_hd.png',
		localised = 'Estonian',
		name = 'Estonia',
	},
	['eswatini'] = {
		flag = 'File:sz_hd.png',
		localised = 'Swazi',
		name = 'Eswatini',
	},
	['ethiopia'] = {
		flag = 'File:et_hd.png',
		localised = 'Ethiopian',
		name = 'Ethiopia',
	},
	['falklandislands'] = {
		flag = 'File:fk_hd.png',
		localised = 'Falkland Islands',
		name = 'Falkland Islands',
	},
	['faroeislands'] = {
		flag = 'File:fo_hd.png',
		localised = 'Faeroese',
		name = 'Faroe Islands',
	},
	['federatedstatesofmicronesia'] = {
		flag = 'File:fm_hd.png',
		localised = 'Micronesian',
		name = 'Federated States of Micronesia',
	},
	['fiji'] = {
		flag = 'File:fj_hd.png',
		localised = 'Fijian',
		name = 'Fiji',
	},
	['finland'] = {
		flag = 'File:fi_hd.png',
		localised = 'Finnish',
		name = 'Finland',
	},
	['france'] = {
		flag = 'File:fr_hd.png',
		localised = 'French',
		name = 'France',
	},
	['frenchguiana'] = {
		flag = 'File:gf_hd.png',
		localised = 'French Guianan',
		name = 'French Guiana',
	},
	['frenchpolynesia'] = {
		flag = 'File:pf_hd.png',
		localised = 'French Polynesian',
		name = 'French Polynesia',
	},
	['frenchsouthernterritories'] = {
		flag = 'File:tf_hd.png',
		localised = 'French',
		name = 'French Southern Territories',
	},
	['gabon'] = {
		flag = 'File:ga_hd.png',
		localised = 'Gabonese',
		name = 'Gabon',
	},
	['gambia'] = {
		flag = 'File:gm_hd.png',
		localised = 'Gambian',
		name = 'Gambia',
	},
	['georgia'] = {
		flag = 'File:ge_hd.png',
		localised = 'Georgian',
		name = 'Georgia',
	},
	['germany'] = {
		flag = 'File:de_hd.png',
		localised = 'German',
		name = 'Germany',
	},
	['ghana'] = {
		flag = 'File:gh_hd.png',
		localised = 'Ghanaian',
		name = 'Ghana',
	},
	['gibraltar'] = {
		flag = 'File:gi_hd.png',
		localised = 'Gibraltarian',
		name = 'Gibraltar',
	},
	['greece'] = {
		flag = 'File:gr_hd.png',
		localised = 'Greek',
		name = 'Greece',
	},
	['greenland'] = {
		flag = 'File:gl_hd.png',
		localised = 'Greenlandic',
		name = 'Greenland',
	},
	['grenada'] = {
		flag = 'File:gd_hd.png',
		localised = 'Grenadian',
		name = 'Grenada',
	},
	['guadeloupe'] = {
		flag = 'File:gp_hd.png',
		localised = 'Guadeloupean',
		name = 'Guadeloupe',
	},
	['guam'] = {
		flag = 'File:gu_hd.png',
		localised = 'Guamanian',
		name = 'Guam',
	},
	['guatemala'] = {
		flag = 'File:gt_hd.png',
		localised = 'Guatemalan',
		name = 'Guatemala',
	},
	['guernsey'] = {
		flag = 'File:gg_hd.png',
		localised = 'Guernsey',
		name = 'Guernsey',
	},
	['guinea'] = {
		flag = 'File:gn_hd.png',
		localised = 'Guinean',
		name = 'Guinea',
	},
	['guinea-bissau'] = {
		flag = 'File:gw_hd.png',
		localised = 'Bissau-Guinean',
		name = 'Guinea-Bissau',
	},
	['guyana'] = {
		flag = 'File:gy_hd.png',
		localised = 'Guyanese',
		name = 'Guyana',
	},
	['haiti'] = {
		flag = 'File:ht_hd.png',
		localised = 'Haitian',
		name = 'Haiti',
	},
	['heardislandandmcdonaldislands'] = {
		flag = 'File:hm_hd.png',
		localised = 'Heard Island',
		name = 'Heard Island and McDonald Islands',
	},
	['honduras'] = {
		flag = 'File:hn_hd.png',
		localised = 'Honduran',
		name = 'Honduras',
	},
	['hongkong'] = {
		flag = 'File:hk_hd.png',
		localised = 'Hong Kong',
		name = 'Hong Kong',
	},
	['hungary'] = {
		flag = 'File:hu_hd.png',
		localised = 'Hungarian',
		name = 'Hungary',
	},
	['iceland'] = {
		flag = 'File:is_hd.png',
		localised = 'Icelandic',
		name = 'Iceland',
	},
	['india'] = {
		flag = 'File:in_hd.png',
		localised = 'Indian',
		name = 'India',
	},
	['indonesia'] = {
		flag = 'File:id_hd.png',
		localised = 'Indonesian',
		name = 'Indonesia',
	},
	['iran'] = {
		flag = 'File:ir_hd.png',
		localised = 'Iranian',
		name = 'Iran',
	},
	['iraq'] = {
		flag = 'File:iq_hd.png',
		localised = 'Iraqi',
		name = 'Iraq',
	},
	['ireland'] = {
		flag = 'File:ie_hd.png',
		localised = 'Irish',
		name = 'Ireland',
	},
	['isleofman'] = {
		flag = 'File:im_hd.png',
		localised = 'Manx',
		name = 'Isle of Man',
	},
	['israel'] = {
		flag = 'File:il_hd.png',
		localised = 'Israeli',
		name = 'Israel',
	},
	['italy'] = {
		flag = 'File:it_hd.png',
		localised = 'Italian',
		name = 'Italy',
	},
	['jamaica'] = {
		flag = 'File:jm_hd.png',
		localised = 'Jamaican',
		name = 'Jamaica',
	},
	['japan'] = {
		flag = 'File:jp_hd.png',
		localised = 'Japanese',
		name = 'Japan',
	},
	['jersey'] = {
		flag = 'File:je_hd.png',
		localised = 'Jersey',
		name = 'Jersey',
	},
	['jordan'] = {
		flag = 'File:jo_hd.png',
		localised = 'Jordanian',
		name = 'Jordan',
	},
	['kazakhstan'] = {
		flag = 'File:kz_hd.png',
		localised = 'Kazakhstani',
		name = 'Kazakhstan',
	},
	['kenya'] = {
		flag = 'File:ke_hd.png',
		localised = 'Kenyan',
		name = 'Kenya',
	},
	['kiribati'] = {
		flag = 'File:ki_hd.png',
		localised = 'I-Kiribati',
		name = 'Kiribati',
	},
	['kuwait'] = {
		flag = 'File:kw_hd.png',
		localised = 'Kuwaiti',
		name = 'Kuwait',
	},
	['kyrgyzstan'] = {
		flag = 'File:kg_hd.png',
		localised = 'Kyrgyz',
		name = 'Kyrgyzstan',
	},
	['laos'] = {
		flag = 'File:la_hd.png',
		localised = 'Laotian',
		name = 'Laos',
	},
	['latvia'] = {
		flag = 'File:lv_hd.png',
		localised = 'Latvian',
		name = 'Latvia',
	},
	['lebanon'] = {
		flag = 'File:lb_hd.png',
		localised = 'Lebanese',
		name = 'Lebanon',
	},
	['lesotho'] = {
		flag = 'File:ls_hd.png',
		localised = 'Basotho',
		name = 'Lesotho',
	},
	['liberia'] = {
		flag = 'File:lr_hd.png',
		localised = 'Liberian',
		name = 'Liberia',
	},
	['libya'] = {
		flag = 'File:ly_hd.png',
		localised = 'Libyan',
		name = 'Libya',
	},
	['liechtenstein'] = {
		flag = 'File:li_hd.png',
		localised = 'Liechtensteiner',
		name = 'Liechtenstein',
	},
	['lithuania'] = {
		flag = 'File:lt_hd.png',
		localised = 'Lithuanian',
		name = 'Lithuania',
	},
	['luxembourg'] = {
		flag = 'File:lu_hd.png',
		localised = 'Luxembourger',
		name = 'Luxembourg',
	},
	['macau'] = {
		flag = 'File:mo_hd.png',
		localised = 'Macau',
		name = 'Macau',
	},
	['madagascar'] = {
		flag = 'File:mg_hd.png',
		localised = 'Malagasy',
		name = 'Madagascar',
	},
	['malawi'] = {
		flag = 'File:mw_hd.png',
		localised = 'Malawian',
		name = 'Malawi',
	},
	['malaysia'] = {
		flag = 'File:my_hd.png',
		localised = 'Malaysian',
		name = 'Malaysia',
	},
	['maldives'] = {
		flag = 'File:mv_hd.png',
		localised = 'Maldivian',
		name = 'Maldives',
	},
	['mali'] = {
		flag = 'File:ml_hd.png',
		localised = 'Malian',
		name = 'Mali',
	},
	['malta'] = {
		flag = 'File:mt_hd.png',
		localised = 'Maltese',
		name = 'Malta',
	},
	['marshallislands'] = {
		flag = 'File:mh_hd.png',
		localised = 'Marshallese',
		name = 'Marshall Islands',
	},
	['martinique'] = {
		flag = 'File:mq_hd.png',
		localised = 'Martiniquais',
		name = 'Martinique',
	},
	['mauritania'] = {
		flag = 'File:mr_hd.png',
		localised = 'Mauritanian',
		name = 'Mauritania',
	},
	['mauritius'] = {
		flag = 'File:mu_hd.png',
		localised = 'Mauritian',
		name = 'Mauritius',
	},
	['mayotte'] = {
		flag = 'File:yt_hd.png',
		localised = 'Mahoran',
		name = 'Mayotte',
	},
	['mexico'] = {
		flag = 'File:mx_hd.png',
		localised = 'Mexican',
		name = 'Mexico',
	},
	['moldova'] = {
		flag = 'File:md_hd.png',
		localised = 'Moldovan',
		name = 'Moldova',
	},
	['monaco'] = {
		flag = 'File:mc_hd.png',
		localised = 'Monegasque',
		name = 'Monaco',
	},
	['mongolia'] = {
		flag = 'File:mn_hd.png',
		localised = 'Mongolian',
		name = 'Mongolia',
	},
	['montenegro'] = {
		flag = 'File:me_hd.png',
		localised = 'Montenegrin',
		name = 'Montenegro',
	},
	['montserrat'] = {
		flag = 'File:ms_hd.png',
		localised = 'Montserratian',
		name = 'Montserrat',
	},
	['morocco'] = {
		flag = 'File:ma_hd.png',
		localised = 'Moroccan',
		name = 'Morocco',
	},
	['mozambique'] = {
		flag = 'File:mz_hd.png',
		localised = 'Mozambican',
		name = 'Mozambique',
	},
	['myanmar'] = {
		flag = 'File:mm_hd.png',
		localised = 'Burmese',
		name = 'Myanmar',
	},
	['namibia'] = {
		flag = 'File:na_hd.png',
		localised = 'Namibian',
		name = 'Namibia',
	},
	['nauru'] = {
		flag = 'File:nr_hd.png',
		localised = 'Nauruan',
		name = 'Nauru',
	},
	['nepal'] = {
		flag = 'File:np_hd.png',
		localised = 'Nepalese',
		name = 'Nepal',
	},
	['netherlands'] = {
		flag = 'File:nl_hd.png',
		localised = 'Dutch',
		name = 'Netherlands',
	},
	['newcaledonia'] = {
		flag = 'File:nc_hd.png',
		localised = 'New Caledonian',
		name = 'New Caledonia',
	},
	['newzealand'] = {
		flag = 'File:nz_hd.png',
		localised = 'New Zealand',
		name = 'New Zealand',
	},
	['nicaragua'] = {
		flag = 'File:ni_hd.png',
		localised = 'Nicaraguan',
		name = 'Nicaragua',
	},
	['niger'] = {
		flag = 'File:ne_hd.png',
		localised = 'Nigerien',
		name = 'Niger',
	},
	['nigeria'] = {
		flag = 'File:ng_hd.png',
		localised = 'Nigerian',
		name = 'Nigeria',
	},
	['niue'] = {
		flag = 'File:nu_hd.png',
		localised = 'Niuean',
		name = 'Niue',
	},
	['norfolkisland'] = {
		flag = 'File:nf_hd.png',
		localised = 'Norfolk Islander',
		name = 'Norfolk Island',
	},
	['northernmarianaislands'] = {
		flag = 'File:mp_hd.png',
		localised = 'Northern Mariana Islands',
		name = 'Northern Mariana Islands',
	},
	['northkorea'] = {
		flag = 'File:kp_hd.png',
		localised = 'North Korean',
		name = 'North Korea',
	},
	['northmacedonia'] = {
		flag = 'File:mk_hd.png',
		localised = 'North Macedonian',
		name = 'North Macedonia',
	},
	['norway'] = {
		flag = 'File:no_hd.png',
		localised = 'Norwegian',
		name = 'Norway',
	},
	['oman'] = {
		flag = 'File:om_hd.png',
		localised = 'Omani',
		name = 'Oman',
	},
	['pakistan'] = {
		flag = 'File:pk_hd.png',
		localised = 'Pakistani',
		name = 'Pakistan',
	},
	['palau'] = {
		flag = 'File:pw_hd.png',
		localised = 'Palauan',
		name = 'Palau',
	},
	['palestine'] = {
		flag = 'File:ps_hd.png',
		localised = 'Palestinian',
		name = 'Palestine',
	},
	['panama'] = {
		flag = 'File:pa_hd.png',
		localised = 'Panamanian',
		name = 'Panama',
	},
	['papuanewguinea'] = {
		flag = 'File:pg_hd.png',
		localised = 'Papua New Guinean',
		name = 'Papua New Guinea',
	},
	['paraguay'] = {
		flag = 'File:py_hd.png',
		localised = 'Paraguayan',
		name = 'Paraguay',
	},
	['peru'] = {
		flag = 'File:pe_hd.png',
		localised = 'Peruvian',
		name = 'Peru',
	},
	['philippines'] = {
		flag = 'File:ph_hd.png',
		localised = 'Filipino',
		name = 'Philippines',
	},
	['pitcairn'] = {
		flag = 'File:pn_hd.png',
		localised = 'Pitcairn Island',
		name = 'Pitcairn',
	},
	['poland'] = {
		flag = 'File:pl_hd.png',
		localised = 'Polish',
		name = 'Poland',
	},
	['portugal'] = {
		flag = 'File:pt_hd.png',
		localised = 'Portuguese',
		name = 'Portugal',
	},
	['puertorico'] = {
		flag = 'File:pr_hd.png',
		localised = 'Puerto Rican',
		name = 'Puerto Rico',
	},
	['qatar'] = {
		flag = 'File:qa_hd.png',
		localised = 'Qatari',
		name = 'Qatar',
	},
	['romania'] = {
		flag = 'File:ro_hd.png',
		localised = 'Romanian',
		name = 'Romania',
	},
	['russia'] = {
		flag = 'File:ru_hd.png',
		localised = 'Russian',
		name = 'Russia',
	},
	['rwanda'] = {
		flag = 'File:rw_hd.png',
		localised = 'Rwandan',
		name = 'Rwanda',
	},
	['réunion'] = {
		flag = 'File:re_hd.png',
		localised = 'Réunionese',
		name = 'Réunion',
	},
	['saintbarthélemy'] = {
		flag = 'File:bl_hd.png',
		localised = 'Barthélemois',
		name = 'Saint Barthélemy',
	},
	['sainthelena'] = {
		flag = 'File:sh_hd.png',
		localised = 'Saint Helenian',
		name = 'Saint Helena',
	},
	['saintkittsandnevis'] = {
		flag = 'File:kn_hd.png',
		localised = 'Saint Kitts and Nevis',
		name = 'Saint Kitts and Nevis',
	},
	['saintlucia'] = {
		flag = 'File:lc_hd.png',
		localised = 'Saint Lucian',
		name = 'Saint Lucia',
	},
	['saintmartin(frenchpart)'] = {
		flag = 'File:mf_hd.png',
		localised = 'Saint-Martinoise',
		name = 'Saint Martin (French part)',
	},
	['saintpierreandmiquelon'] = {
		flag = 'File:pm_hd.png',
		localised = 'Miquelonnais',
		name = 'Saint Pierre and Miquelon',
	},
	['saintvincentandthegrenadines'] = {
		flag = 'File:vc_hd.png',
		localised = 'Saint Vincent and the Grenadines',
		name = 'Saint Vincent and the Grenadines',
	},
	['samoa'] = {
		flag = 'File:ws_hd.png',
		localised = 'Samoan',
		name = 'Samoa',
	},
	['sanmarino'] = {
		flag = 'File:sm_hd.png',
		localised = 'Sammarinese',
		name = 'San Marino',
	},
	['saotomeandprincipe'] = {
		flag = 'File:st_hd.png',
		localised = 'São Toméan',
		name = 'Sao Tome and Principe',
	},
	['saudiarabia'] = {
		flag = 'File:sa_hd.png',
		localised = 'Saudi Arabian',
		name = 'Saudi Arabia',
	},
	['senegal'] = {
		flag = 'File:sn_hd.png',
		localised = 'Senegalese',
		name = 'Senegal',
	},
	['serbia'] = {
		flag = 'File:rs_hd.png',
		localised = 'Serbian',
		name = 'Serbia',
	},
	['seychelles'] = {
		flag = 'File:sc_hd.png',
		localised = 'Scottish',
		name = 'Seychelles',
	},
	['sierraleone'] = {
		flag = 'File:sl_hd.png',
		localised = 'Sierra Leonean',
		name = 'Sierra Leone',
	},
	['singapore'] = {
		flag = 'File:sg_hd.png',
		localised = 'Singaporean',
		name = 'Singapore',
	},
	['sintmaarten(dutchpart)'] = {
		flag = 'File:sx_hd.png',
		localised = 'Sint Maarten',
		name = 'Sint Maarten (Dutch part)',
	},
	['slovakia'] = {
		flag = 'File:sk_hd.png',
		localised = 'Slovak',
		name = 'Slovakia',
	},
	['slovenia'] = {
		flag = 'File:si_hd.png',
		localised = 'Slovenian',
		name = 'Slovenia',
	},
	['solomonislands'] = {
		flag = 'File:sb_hd.png',
		localised = 'Solomon Islands',
		name = 'Solomon Islands',
	},
	['somalia'] = {
		flag = 'File:so_hd.png',
		localised = 'Somali',
		name = 'Somalia',
	},
	['southafrica'] = {
		flag = 'File:za_hd.png',
		localised = 'South African',
		name = 'South Africa',
	},
	['southgeorgiaandthesouthsandwichislands'] = {
		flag = 'File:gs_hd.png',
		localised = 'South Georgia Island',
		name = 'South Georgia and the South Sandwich Islands',
	},
	['southkorea'] = {
		flag = 'File:kr_hd.png',
		localised = 'Korean',
		name = 'South Korea',
	},
	['southsudan'] = {
		flag = 'File:ss_hd.png',
		localised = 'South Sudanese',
		name = 'South Sudan',
	},
	['spain'] = {
		flag = 'File:es_hd.png',
		localised = 'Spanish',
		name = 'Spain',
	},
	['srilanka'] = {
		flag = 'File:lk_hd.png',
		localised = 'Sri Lankan',
		name = 'Sri Lanka',
	},
	['sudan'] = {
		flag = 'File:sd_hd.png',
		localised = 'Sudanese',
		name = 'Sudan',
	},
	['suriname'] = {
		flag = 'File:sr_hd.png',
		localised = 'Surinamese',
		name = 'Suriname',
	},
	['svalbardandjanmayen'] = {
		flag = 'File:sj_hd.png',
		localised = 'Jan Mayen',
		name = 'Svalbard and Jan Mayen',
	},
	['sweden'] = {
		flag = 'File:se_hd.png',
		localised = 'Swedish',
		name = 'Sweden',
	},
	['switzerland'] = {
		flag = 'File:ch_hd.png',
		localised = 'Swiss',
		name = 'Switzerland',
	},
	['syria'] = {
		flag = 'File:sy_hd.png',
		localised = 'Syrian',
		name = 'Syria',
	},
	['taiwan'] = {
		flag = 'File:tw_hd.png',
		localised = 'Taiwanese',
		name = 'Taiwan',
	},
	['tajikistan'] = {
		flag = 'File:tj_hd.png',
		localised = 'Tajik',
		name = 'Tajikistan',
	},
	['tanzania'] = {
		flag = 'File:tz_hd.png',
		localised = 'Tanzanian',
		name = 'Tanzania',
	},
	['thailand'] = {
		flag = 'File:th_hd.png',
		localised = 'Thai',
		name = 'Thailand',
	},
	['timor-leste'] = {
		flag = 'File:tl_hd.png',
		localised = 'Timorese',
		name = 'Timor-Leste',
	},
	['togo'] = {
		flag = 'File:tg_hd.png',
		localised = 'Togolese',
		name = 'Togo',
	},
	['tokelau'] = {
		flag = 'File:tk_hd.png',
		localised = 'Tokelauan',
		name = 'Tokelau',
	},
	['tonga'] = {
		flag = 'File:to_hd.png',
		localised = 'Tongan',
		name = 'Tonga',
	},
	['trinidadandtobago'] = {
		flag = 'File:tt_hd.png',
		localised = 'Trinidadian and Tobagonian',
		name = 'Trinidad and Tobago',
	},
	['tristandacunha'] = {
		flag = 'File:sh-ta hd.png',
		localised = 'Saint Helenian',
		name = 'Tristan da Cunha',
	},
	['tunisia'] = {
		flag = 'File:tn_hd.png',
		localised = 'Tunisian',
		name = 'Tunisia',
	},
	['turkey'] = {
		flag = 'File:tr_hd.png',
		localised = 'Turkish',
		name = 'Turkey',
	},
	['turkmenistan'] = {
		flag = 'File:tm_hd.png',
		localised = 'Turkmen',
		name = 'Turkmenistan',
	},
	['turksandcaicosislands'] = {
		flag = 'File:tc_hd.png',
		localised = 'Turks and Caicos Islands',
		name = 'Turks and Caicos Islands',
	},
	['tuvalu'] = {
		flag = 'File:tv_hd.png',
		localised = 'Tuvaluan',
		name = 'Tuvalu',
	},
	['uganda'] = {
		flag = 'File:ug_hd.png',
		localised = 'Ugandan',
		name = 'Uganda',
	},
	['ukraine'] = {
		flag = 'File:ua_hd.png',
		localised = 'Ukrainian',
		name = 'Ukraine',
	},
	['unitedarabemirates'] = {
		flag = 'File:ae_hd.png',
		localised = 'Emirati',
		name = 'United Arab Emirates',
	},
	['unitedkingdom'] = {
		flag = 'File:gb_hd.png',
		localised = 'British',
		name = 'United Kingdom',
	},
	['unitedstates'] = {
		flag = 'File:us_hd.png',
		localised = 'American',
		name = 'United States',
	},
	['unitedstatesminoroutlyingislands'] = {
		flag = 'File:um_hd.png',
		localised = 'American Islander',
		name = 'United States Minor Outlying Islands',
	},
	['uruguay'] = {
		flag = 'File:uy_hd.png',
		localised = 'Uruguayan',
		name = 'Uruguay',
	},
	['uzbekistan'] = {
		flag = 'File:uz_hd.png',
		localised = 'Uzbek',
		name = 'Uzbekistan',
	},
	['vanuatu'] = {
		flag = 'File:vu_hd.png',
		localised = 'Vanuatuan',
		name = 'Vanuatu',
	},
	['vaticancity'] = {
		flag = 'File:va_hd.png',
		localised = 'Vaticans',
		name = 'Vatican City',
	},
	['venezuela'] = {
		flag = 'File:ve_hd.png',
		localised = 'Venezuelan',
		name = 'Venezuela',
	},
	['vietnam'] = {
		flag = 'File:vn_hd.png',
		localised = 'Vietnamese',
		name = 'Vietnam',
	},
	['virginislands(british)'] = {
		flag = 'File:vg_hd.png',
		localised = 'British Virgin Island',
		name = 'Virgin Islands (British)',
	},
	['virginislands(u.s.)'] = {
		flag = 'File:vi_hd.png',
		localised = 'U.S. Virgin Island',
		name = 'Virgin Islands (U.S.)',
	},
	['wallisandfutuna'] = {
		flag = 'File:wf_hd.png',
		localised = 'Wallis and Futuna',
		name = 'Wallis and Futuna',
	},
	['westernsahara'] = {
		flag = 'File:eh_hd.png',
		localised = 'Western Saharan',
		name = 'Western Sahara',
	},
	['yemen'] = {
		flag = 'File:ye_hd.png',
		localised = 'Yemeni',
		name = 'Yemen',
	},
	['zambia'] = {
		flag = 'File:zm_hd.png',
		localised = 'Zambian',
		name = 'Zambia',
	},
	['zimbabwe'] = {
		flag = 'File:zw_hd.png',
		localised = 'Zimbabwean',
		name = 'Zimbabwe',
	},
	['ålandislands'] = {
		flag = 'File:ax_hd.png',
		localised = 'Ålander',
		name = 'Åland Islands',
	},

	-- ISO 3166-1 alpha-2 User-assigned Code Elements
	['kosovo'] = {
		flag = 'File:xk_hd.png',
		localised = 'Kosovan',
		name = 'Kosovo',
	},

	-- ISO 3166-1 alpha-2 Exceptional Reservations
	['europeanunion'] = {
		flag = 'File:eu_hd.png',
		localised = 'European',
		name = 'Europe',
	},
	['unitednations'] = {
		flag = 'File:un_hd.png',
		localised = 'Global',
		name = 'United Nations',
	},
	['ussr'] = {
		flag = 'File:ussr_hd.png',
		localised = 'Soviet',
		name = 'USSR',
	},

	-- ISO 3166-1 alpha-2 Traditional Reservations
	['yugoslavia'] = {
		flag = 'File:yu_hd.png',
		localised = 'Yugoslavian',
		name = 'Yugoslavia',
	},

	-- ISO 3166-2:GB
	['england'] = {
		flag = 'File:gb-eng hd.png',
		localised = 'English',
		name = 'England',
	},
	['northernireland'] = {
		flag = 'File:gb-nir hd.png',
		localised = 'Northern Irish',
		name = 'Northern Ireland',
	},
	['scotland'] = {
		flag = 'File:gb-sct hd.png',
		localised = 'Scottish',
		name = 'Scotland',
	},
	['wales'] = {
		flag = 'File:gb-wls hd.png',
		localised = 'Welsh',
		name = 'Wales',
	},

	-- Other
	['africa'] = {
		flag = 'File:african union hd.png',
		localised = 'African',
		name = 'Africa',
	},
	['asia'] = {
		flag = 'File:Asia flag hd.png',
		localised = 'Asian',
		name = 'Asia',
	},
	['asia-pacific'] = {
		flag = 'File:Asia-pacific flag hd.png',
		localised = 'APAC',
		name = 'Asia-Pacific',
	},
	['benelux'] = {
		flag = 'File:benelux hd.png',
		localised = 'Benelux',
		name = 'Benelux',
	},
	['centralamerica'] = {
		flag = 'File:cais flag hd.png',
		localised = 'Central America',
		name = 'Central America',
	},
	['centralasia'] = {
		flag = 'File:Space filler flag.png',
		localised = 'Central Asian',
		name = 'Central Asia',
	},
	['commonwealthofindependentstates'] = {
		flag = 'File:Cis hd.png',
		localised = 'CIS',
		name = 'CIS',
	},
	['eastasia'] = {
		flag = 'File:East asia flag hd.png',
		localised = 'East Asian',
		name = 'East Asia',
	},
	['iberia'] = {
		flag = 'File:EsPt hd.png',
		localised = 'Iberian',
		name = 'Iberia',
	},
	['latinamerica'] = {
		flag = 'File:Space filler flag.png',
		localised = 'Latin American',
		name = 'Latin America',
	},
	['latinamericanorth'] = {
		flag = 'File:MxCo hd.png',
		localised = 'Latin America North',
		name = 'Latin America North',
	},
	['latinamericasouth'] = {
		flag = 'File:ClAr hd.png',
		localised = 'Latin America South',
		name = 'Latin America South',
	},
	['middleeast'] = {
		flag = 'File:Middle east flag hd.png',
		localised = 'Middle Eastern',
		name = 'Middle East',
	},
	['nordiccountries'] = {
		flag = 'File:Nordic hd.png',
		localised = 'Nordic',
		name = 'Nordic Countries',
	},
	['northafrica'] = {
		flag = 'File:Space filler flag.png',
		localised = 'North African',
		name = 'North Africa',
	},
	['northamerica'] = {
		flag = 'File:UsCa hd.png',
		localised = 'North American',
		name = 'North America',
	},
	['northeastasia'] = {
		flag = 'File:Northeast Asia flag hd.png',
		localised = 'Northeast Asian',
		name = 'Northeast Asia',
	},
	['oceania'] = {
		flag = 'File:anz hd.png',
		localised = 'Oceanian',
		name = 'Oceania',
	},
	['persiangulfstates'] = {
		flag = 'File:Space filler flag.png',
		localised = 'Persian Gulf State',
		name = 'Persian Gulf States',
	},
	['southamerica'] = {
		flag = 'File:Unasur hd.png',
		localised = 'South American',
		name = 'South America',
	},
	['southasia'] = {
		flag = 'File:south asia flag hd.png',
		localised = 'South Asian',
		name = 'South Asia',
	},
	['southeastasia'] = {
		flag = 'File:asean hd.png',
		localised = 'Southeast Asian',
		name = 'Southeast Asia',
	},
	['world'] = {
		flag = 'File:World hd.png',
		localised = 'Global',
		name = 'World',
	},

	['englishspeaking'] = {
		flag = 'File:UsGb hd.png',
		localised = '',
		name = 'English Speaking',
	},
	['germanspeaking'] = {
		flag = 'File:DeAt hd.png',
		localised = '',
		name = 'German Speaking',
	},
	['spanishspeaking'] = {
		flag = 'File:EsMx hd.png',
		localised = '',
		name = 'Spanish Speaking',
	},
	['portuguesespeaking'] = {
		flag = 'File:PtBr hd.png',
		localised = '',
		name = 'Portuguese Speaking',
	},
	['russianspeaking'] = {
		flag = 'File:RuBy hd.png',
		localised = '',
		name = 'Russian Speaking',
	},
	['non-representing'] = {
		flag = 'File:non hd.png',
		localised = 'non-country representing',
		name = 'Non-representing',
	},
	['filler'] = {
		flag = 'File:Space filler flag.png',
		localised = '',
		name = '',
	},
}

-- This table includes:
--   ISO 3166-1 alpha-2
--   ISO 3166-1 alpha-2 User-assigned Code Elements
--   ISO 3166-1 alpha-2 Exceptional Reservations
--   ISO 3166-1 alpha-2 Traditional Reservations
local twoLetter = {
	['ad'] = 'andorra',
	['ae'] = 'unitedarabemirates',
	['af'] = 'afghanistan',
	['ag'] = 'antiguaandbarbuda',
	['ai'] = 'anguilla',
	['al'] = 'albania',
	['am'] = 'armenia',
	['ao'] = 'angola',
	['aq'] = 'antarctica',
	['ar'] = 'argentina',
	['as'] = 'americansamoa',
	['ac'] = 'ascensionisland',
	['at'] = 'austria',
	['au'] = 'australia',
	['aw'] = 'aruba',
	['ax'] = 'ålandislands',
	['az'] = 'azerbaijan',
	['ba'] = 'bosniaandherzegovina',
	['bb'] = 'barbados',
	['bd'] = 'bangladesh',
	['be'] = 'belgium',
	['bf'] = 'burkinafaso',
	['bg'] = 'bulgaria',
	['bh'] = 'bahrain',
	['bi'] = 'burundi',
	['bj'] = 'benin',
	['bl'] = 'saintbarthélemy',
	['bm'] = 'bermuda',
	['bn'] = 'brunei',
	['bo'] = 'bolivia',
	['bq'] = 'bonaire,sinteustatiusandsaba',
	['br'] = 'brazil',
	['bs'] = 'bahamas',
	['bt'] = 'bhutan',
	['bv'] = 'bouvetisland',
	['bw'] = 'botswana',
	['by'] = 'belarus',
	['bz'] = 'belize',
	['ca'] = 'canada',
	['cc'] = 'cocos(keeling)islands',
	['cd'] = 'congo,democraticrepublicofthe',
	['cf'] = 'centralafricanrepublic',
	['cg'] = 'congo',
	['ch'] = 'switzerland',
	['ci'] = 'côted\'ivoire',
	['ck'] = 'cookislands',
	['cl'] = 'chile',
	['cm'] = 'cameroon',
	['cn'] = 'china',
	['co'] = 'colombia',
	['cr'] = 'costarica',
	['cu'] = 'cuba',
	['cv'] = 'caboverde',
	['cw'] = 'curaçao',
	['cx'] = 'christmasisland',
	['cy'] = 'cyprus',
	['cz'] = 'czechia',
	['de'] = 'germany',
	['dj'] = 'djibouti',
	['dk'] = 'denmark',
	['dm'] = 'dominica',
	['do'] = 'dominicanrepublic',
	['dz'] = 'algeria',
	['ec'] = 'ecuador',
	['ee'] = 'estonia',
	['eg'] = 'egypt',
	['eh'] = 'westernsahara',
	['er'] = 'eritrea',
	['es'] = 'spain',
	['et'] = 'ethiopia',
	['fi'] = 'finland',
	['fj'] = 'fiji',
	['fk'] = 'falklandislands',
	['fm'] = 'micronesia',
	['fo'] = 'faroeislands',
	['fr'] = 'france',
	['ga'] = 'gabon',
	['gb'] = 'unitedkingdom',
	['gd'] = 'grenada',
	['ge'] = 'georgia',
	['gf'] = 'frenchguiana',
	['gg'] = 'guernsey',
	['gh'] = 'ghana',
	['gi'] = 'gibraltar',
	['gl'] = 'greenland',
	['gm'] = 'gambia',
	['gn'] = 'guinea',
	['gp'] = 'guadeloupe',
	['gq'] = 'equatorialguinea',
	['gr'] = 'greece',
	['gs'] = 'southgeorgiaandthesouthsandwichislands',
	['gt'] = 'guatemala',
	['gu'] = 'guam',
	['gw'] = 'guinea-bissau',
	['gy'] = 'guyana',
	['hk'] = 'hongkong',
	['hm'] = 'heardislandandmcdonaldislands',
	['hn'] = 'honduras',
	['hr'] = 'croatia',
	['ht'] = 'haiti',
	['hu'] = 'hungary',
	['id'] = 'indonesia',
	['ie'] = 'ireland',
	['il'] = 'israel',
	['im'] = 'isleofman',
	['in'] = 'india',
	['io'] = 'britishindianoceanterritory',
	['iq'] = 'iraq',
	['ir'] = 'iran',
	['is'] = 'iceland',
	['it'] = 'italy',
	['je'] = 'jersey',
	['jm'] = 'jamaica',
	['jo'] = 'jordan',
	['jp'] = 'japan',
	['ke'] = 'kenya',
	['kg'] = 'kyrgyzstan',
	['kh'] = 'cambodia',
	['ki'] = 'kiribati',
	['km'] = 'comoros',
	['kn'] = 'saintkittsandnevis',
	['kp'] = 'northkorea',
	['kr'] = 'southkorea',
	['kw'] = 'kuwait',
	['ky'] = 'caymanislands',
	['kz'] = 'kazakhstan',
	['la'] = 'laos',
	['lb'] = 'lebanon',
	['lc'] = 'saintlucia',
	['li'] = 'liechtenstein',
	['lk'] = 'srilanka',
	['lr'] = 'liberia',
	['ls'] = 'lesotho',
	['lt'] = 'lithuania',
	['lu'] = 'luxembourg',
	['lv'] = 'latvia',
	['ly'] = 'libya',
	['ma'] = 'morocco',
	['mc'] = 'monaco',
	['md'] = 'moldova',
	['me'] = 'montenegro',
	['mf'] = 'saintmartin(frenchpart)',
	['mg'] = 'madagascar',
	['mh'] = 'marshallislands',
	['mk'] = 'northmacedonia',
	['ml'] = 'mali',
	['mm'] = 'myanmar',
	['mn'] = 'mongolia',
	['mo'] = 'macau',
	['mp'] = 'northernmarianaislands',
	['mq'] = 'martinique',
	['mr'] = 'mauritania',
	['ms'] = 'montserrat',
	['mt'] = 'malta',
	['mu'] = 'mauritius',
	['mv'] = 'maldives',
	['mw'] = 'malawi',
	['mx'] = 'mexico',
	['my'] = 'malaysia',
	['mz'] = 'mozambique',
	['na'] = 'namibia',
	['nc'] = 'newcaledonia',
	['ne'] = 'niger',
	['nf'] = 'norfolkisland',
	['ng'] = 'nigeria',
	['ni'] = 'nicaragua',
	['nl'] = 'netherlands',
	['no'] = 'norway',
	['np'] = 'nepal',
	['nr'] = 'nauru',
	['nu'] = 'niue',
	['nz'] = 'newzealand',
	['om'] = 'oman',
	['pa'] = 'panama',
	['pe'] = 'peru',
	['pf'] = 'frenchpolynesia',
	['pg'] = 'papuanewguinea',
	['ph'] = 'philippines',
	['pk'] = 'pakistan',
	['pl'] = 'poland',
	['pm'] = 'saintpierreandmiquelon',
	['pn'] = 'pitcairn',
	['pr'] = 'puertorico',
	['ps'] = 'palestine',
	['pt'] = 'portugal',
	['pw'] = 'palau',
	['py'] = 'paraguay',
	['qa'] = 'qatar',
	['re'] = 'réunion',
	['ro'] = 'romania',
	['rs'] = 'serbia',
	['ru'] = 'russia',
	['rw'] = 'rwanda',
	['sa'] = 'saudiarabia',
	['sb'] = 'solomonislands',
	['sc'] = 'seychelles',
	['sd'] = 'sudan',
	['se'] = 'sweden',
	['sg'] = 'singapore',
	['sh'] = 'sainthelena',
	['si'] = 'slovenia',
	['sj'] = 'svalbardandjanmayen',
	['sk'] = 'slovakia',
	['sl'] = 'sierraleone',
	['sm'] = 'sanmarino',
	['sn'] = 'senegal',
	['so'] = 'somalia',
	['sr'] = 'suriname',
	['ss'] = 'southsudan',
	['st'] = 'saotomeandprincipe',
	['sv'] = 'elsalvador',
	['sx'] = 'sintmaarten(dutchpart)',
	['sy'] = 'syria',
	['sz'] = 'eswatini',
	['tc'] = 'turksandcaicosislands',
	['td'] = 'chad',
	['tf'] = 'frenchsouthernterritories',
	['tg'] = 'togo',
	['th'] = 'thailand',
	['tj'] = 'tajikistan',
	['tk'] = 'tokelau',
	['tl'] = 'timor-leste',
	['tm'] = 'turkmenistan',
	['tn'] = 'tunisia',
	['to'] = 'tonga',
	['tr'] = 'turkey',
	['tt'] = 'trinidadandtobago',
	['tv'] = 'tuvalu',
	['tw'] = 'taiwan',
	['tz'] = 'tanzania',
	['ua'] = 'ukraine',
	['ug'] = 'uganda',
	['um'] = 'unitedstatesminoroutlyingislands',
	['us'] = 'unitedstates',
	['uy'] = 'uruguay',
	['uz'] = 'uzbekistan',
	['va'] = 'vaticancity',
	['vc'] = 'saintvincentandthegrenadines',
	['ve'] = 'venezuela',
	['vg'] = 'virginislands(british)',
	['vi'] = 'virginislands(u.s.)',
	['vn'] = 'vietnam',
	['vu'] = 'vanuatu',
	['wf'] = 'wallisandfutuna',
	['ws'] = 'samoa',
	['ye'] = 'yemen',
	['yt'] = 'mayotte',
	['za'] = 'southafrica',
	['zm'] = 'zambia',
	['zw'] = 'zimbabwe',

	--   ISO 3166-1 alpha-2 User-assigned Code Elements
	['xk'] = 'kosovo',
	['xx'] = 'non-representing',

	--   ISO 3166-1 alpha-2 Exceptional Reservations
	['eu'] = 'europeanunion',
	['uk'] = 'unitedkingdom',
	['un'] = 'unitednations',

	--   ISO 3166-1 alpha-2 Traditional Reservations
	['yu'] = 'yugoslavia',
}

-- This table includes:
--   ISO 3166-1 alpha-3
--   ISO 3166-2:GB
--   Other
local threeLetter = {
	-- ISO 3166-1 alpha-3
	['abw'] = 'aruba',
	['afg'] = 'afghanistan',
	['ago'] = 'angola',
	['aia'] = 'anguilla',
	['ala'] = 'ålandislands',
	['alb'] = 'albania',
	['and'] = 'andorra',
	['are'] = 'unitedarabemirates',
	['arg'] = 'argentina',
	['arm'] = 'armenia',
	['asm'] = 'americansamoa',
	['ata'] = 'antarctica',
	['atf'] = 'frenchsouthernterritories',
	['atg'] = 'antiguaandbarbuda',
	['aus'] = 'australia',
	['aut'] = 'austria',
	['aze'] = 'azerbaijan',
	['bdi'] = 'burundi',
	['bel'] = 'belgium',
	['ben'] = 'benin',
	['bes'] = 'bonaire,sinteustatiusandsaba',
	['bfa'] = 'burkinafaso',
	['bgd'] = 'bangladesh',
	['bgr'] = 'bulgaria',
	['bhr'] = 'bahrain',
	['bhs'] = 'bahamas',
	['bih'] = 'bosniaandherzegovina',
	['blm'] = 'saintbarthélemy',
	['blr'] = 'belarus',
	['blz'] = 'belize',
	['bmu'] = 'bermuda',
	['bol'] = 'bolivia',
	['bra'] = 'brazil',
	['brb'] = 'barbados',
	['brn'] = 'brunei',
	['btn'] = 'bhutan',
	['bvt'] = 'bouvetisland',
	['bwa'] = 'botswana',
	['caf'] = 'centralafricanrepublic',
	['can'] = 'canada',
	['cck'] = 'cocos(keeling)islands',
	['che'] = 'switzerland',
	['chl'] = 'chile',
	['chn'] = 'china',
	['civ'] = 'côted\'ivoire',
	['cmr'] = 'cameroon',
	['cod'] = 'congo,democraticrepublicofthe',
	['cog'] = 'congo',
	['cok'] = 'cookislands',
	['col'] = 'colombia',
	['com'] = 'comoros',
	['cpv'] = 'caboverde',
	['cri'] = 'costarica',
	['cub'] = 'cuba',
	['cuw'] = 'curaçao',
	['cxr'] = 'christmasisland',
	['cym'] = 'caymanislands',
	['cyp'] = 'cyprus',
	['cze'] = 'czechia',
	['deu'] = 'germany',
	['dji'] = 'djibouti',
	['dma'] = 'dominica',
	['dnk'] = 'denmark',
	['dom'] = 'dominicanrepublic',
	['dza'] = 'algeria',
	['ecu'] = 'ecuador',
	['egy'] = 'egypt',
	['eri'] = 'eritrea',
	['esh'] = 'westernsahara',
	['esp'] = 'spain',
	['est'] = 'estonia',
	['eth'] = 'ethiopia',
	['fin'] = 'finland',
	['fji'] = 'fiji',
	['flk'] = 'falklandislands(malvinas)',
	['fra'] = 'france',
	['fro'] = 'faroeislands',
	['fsm'] = 'micronesia',
	['gab'] = 'gabon',
	['gbr'] = 'unitedkingdom',
	['geo'] = 'georgia',
	['ggy'] = 'guernsey',
	['gha'] = 'ghana',
	['gib'] = 'gibraltar',
	['gin'] = 'guinea',
	['glp'] = 'guadeloupe',
	['gmb'] = 'gambia',
	['gnb'] = 'guinea-bissau',
	['gnq'] = 'equatorialguinea',
	['grc'] = 'greece',
	['grd'] = 'grenada',
	['grl'] = 'greenland',
	['gtm'] = 'guatemala',
	['guf'] = 'frenchguiana',
	['gum'] = 'guam',
	['guy'] = 'guyana',
	['hkg'] = 'hongkong',
	['hmd'] = 'heardislandandmcdonaldislands',
	['hnd'] = 'honduras',
	['hrv'] = 'croatia',
	['hti'] = 'haiti',
	['hun'] = 'hungary',
	['idn'] = 'indonesia',
	['imn'] = 'isleofman',
	['ind'] = 'india',
	['iot'] = 'britishindianoceanterritory',
	['irl'] = 'ireland',
	['irn'] = 'iran',
	['irq'] = 'iraq',
	['isl'] = 'iceland',
	['isr'] = 'israel',
	['ita'] = 'italy',
	['jam'] = 'jamaica',
	['jey'] = 'jersey',
	['jor'] = 'jordan',
	['jpn'] = 'japan',
	['kaz'] = 'kazakhstan',
	['ken'] = 'kenya',
	['kgz'] = 'kyrgyzstan',
	['khm'] = 'cambodia',
	['kir'] = 'kiribati',
	['kna'] = 'saintkittsandnevis',
	['kor'] = 'southkorea',
	['kwt'] = 'kuwait',
	['lao'] = 'laos',
	['lbn'] = 'lebanon',
	['lbr'] = 'liberia',
	['lby'] = 'libya',
	['lca'] = 'saintlucia',
	['lie'] = 'liechtenstein',
	['lka'] = 'srilanka',
	['lso'] = 'lesotho',
	['ltu'] = 'lithuania',
	['lux'] = 'luxembourg',
	['lva'] = 'latvia',
	['mac'] = 'macau',
	['maf'] = 'saintmartin(frenchpart)',
	['mar'] = 'morocco',
	['mco'] = 'monaco',
	['mda'] = 'moldova',
	['mdg'] = 'madagascar',
	['mdv'] = 'maldives',
	['mex'] = 'mexico',
	['mhl'] = 'marshallislands',
	['mkd'] = 'northmacedonia',
	['mli'] = 'mali',
	['mlt'] = 'malta',
	['mmr'] = 'myanmar',
	['mne'] = 'montenegro',
	['mng'] = 'mongolia',
	['mnp'] = 'northernmarianaislands',
	['moz'] = 'mozambique',
	['mrt'] = 'mauritania',
	['msr'] = 'montserrat',
	['mtq'] = 'martinique',
	['mus'] = 'mauritius',
	['mwi'] = 'malawi',
	['mys'] = 'malaysia',
	['myt'] = 'mayotte',
	['nam'] = 'namibia',
	['ncl'] = 'newcaledonia',
	['ner'] = 'niger',
	['nfk'] = 'norfolkisland',
	['nga'] = 'nigeria',
	['nic'] = 'nicaragua',
	['niu'] = 'niue',
	['nld'] = 'netherlands',
	['nor'] = 'norway',
	['npl'] = 'nepal',
	['nru'] = 'nauru',
	['nzl'] = 'newzealand',
	['omn'] = 'oman',
	['pak'] = 'pakistan',
	['pan'] = 'panama',
	['pcn'] = 'pitcairn',
	['per'] = 'peru',
	['phl'] = 'philippines',
	['plw'] = 'palau',
	['png'] = 'papuanewguinea',
	['pol'] = 'poland',
	['pri'] = 'puertorico',
	['prk'] = 'northkorea',
	['prt'] = 'portugal',
	['pry'] = 'paraguay',
	['pse'] = 'palestine',
	['pyf'] = 'frenchpolynesia',
	['qat'] = 'qatar',
	['reu'] = 'réunion',
	['rou'] = 'romania',
	['rus'] = 'russia',
	['rwa'] = 'rwanda',
	['sau'] = 'saudiarabia',
	['sdn'] = 'sudan',
	['sen'] = 'senegal',
	['sgp'] = 'singapore',
	['sgs'] = 'southgeorgiaandthesouthsandwichislands',
	['shn'] = 'sainthelena',
	['sjm'] = 'svalbardandjanmayen',
	['slb'] = 'solomonislands',
	['sle'] = 'sierraleone',
	['slv'] = 'elsalvador',
	['smr'] = 'sanmarino',
	['som'] = 'somalia',
	['spm'] = 'saintpierreandmiquelon',
	['srb'] = 'serbia',
	['ssd'] = 'southsudan',
	['stp'] = 'saotomeandprincipe',
	['sur'] = 'suriname',
	['svk'] = 'slovakia',
	['svn'] = 'slovenia',
	['swe'] = 'sweden',
	['swz'] = 'eswatini',
	['sxm'] = 'sintmaarten(dutchpart)',
	['syc'] = 'seychelles',
	['syr'] = 'syria',
	['tca'] = 'turksandcaicosislands',
	['tcd'] = 'chad',
	['tgo'] = 'togo',
	['tha'] = 'thailand',
	['tjk'] = 'tajikistan',
	['tkl'] = 'tokelau',
	['tkm'] = 'turkmenistan',
	['tls'] = 'timor-leste',
	['ton'] = 'tonga',
	['tto'] = 'trinidadandtobago',
	['tun'] = 'tunisia',
	['tur'] = 'turkey',
	['tuv'] = 'tuvalu',
	['twn'] = 'taiwan',
	['tza'] = 'tanzania',
	['uga'] = 'uganda',
	['ukr'] = 'ukraine',
	['umi'] = 'unitedstatesminoroutlyingislands',
	['ury'] = 'uruguay',
	['usa'] = 'unitedstates',
	['uzb'] = 'uzbekistan',
	['vat'] = 'vaticancity',
	['vct'] = 'saintvincentandthegrenadines',
	['ven'] = 'venezuela(bolivarianrepublicof)',
	['vgb'] = 'virginislands(british)',
	['vir'] = 'virginislands(u.s.)',
	['vnm'] = 'vietnam',
	['vut'] = 'vanuatu',
	['wlf'] = 'wallisandfutuna',
	['wsm'] = 'samoa',
	['yem'] = 'yemen',
	['zaf'] = 'southafrica',
	['zmb'] = 'zambia',
	['zwe'] = 'zimbabwe',

	-- ISO 3166-2:GB
	['eng'] = 'england',
	['nir'] = 'northernireland',
	['sct'] = 'scotland',
	['wls'] = 'wales',

	-- Other
	['anz'] = 'oceania',
	['cis'] = 'commonwealthofindependentstates',
	['int'] = 'world',
	['lan']	= 'latinamericanorth',
	['las']	= 'latinamericasouth',
	['sam'] = 'southamerica',
	['sca'] = 'scandinavia',
	['sea'] = 'southeastasia',
	['uae'] = 'unitedarabemirates',

	['tbd'] = 'filler',
}

-- This table includes:
--   ISO 3166-3
--   Accents/special characters
--   Other
local aliases = {
	-- ISO 3166-3
	['suhh'] = 'ussr',
	['yucs'] = 'yugoslavia',

	-- Accents/special characters
	['aland'] = 'ålandislands',
	['Ålandislands'] = 'ålandislands',
	['curacao'] = 'curaçao',
	['ivorycoast'] = 'côted\'ivoire',

	-- Other
	['america'] = 'unitedstates',
	['americas'] = 'northamerica',
	['asiapacific'] = 'asia-pacific',
	['apac'] = 'asia-pacific',
	['bonaire'] = 'bonaire,sinteustatiusandsaba',
	['sinteustatius'] = 'bonaire,sinteustatiusandsaba',
	['saba'] = 'bonaire,sinteustatiusandsaba',
	['caribbeannetherlands'] = 'bonaire,sinteustatiusandsaba',
	['bosnia'] = 'bosniaandherzegovina',
	['bosnia&herzegovina'] = 'bosniaandherzegovina',
	['bruneidarussalam'] = 'brunei',
	['democraticrepublicofthecongo'] = 'congo,democraticrepublicofthe',
	['republicofthecongo'] = 'congo',
	['cocosislands'] = 'cocos(keeling)islands',
	['keelingislands'] = 'cocos(keeling)islands',
	['czech'] = 'czechia',
	['czechrepublic'] = 'czechia',
	['europe'] = 'europeanunion',
	['greatbritain'] = 'unitedkingdom',
	['britain'] = 'unitedkingdom',
	['holland'] = 'netherlands',
	['international'] = 'world',
	['korea'] = 'southkorea',
	['latam'] = 'latinamerica',
	['macao'] = 'macau',
	['nea'] = 'northeastasia',
	['nord'] = 'nordiccountries',
	['nordic'] = 'nordiccountries',
	['nordiccouncil'] = 'nordiccountries',
	['macedonia'] = 'northmacedonia',
	['makedonia'] = 'northmacedonia',
	['micronesia'] = 'federatedstatesofmicronesia',
	['republic of macedonia'] = 'northmacedonia',
	['scandinavia'] = 'nordiccountries',
	['saintmartin'] = 'saintmartin(frenchpart)',
	['sintmaarten'] = 'sintmaarten(dutchpart)',
	['slovakrepublic'] = 'slovakia',
	['chinesetaipei'] = 'taiwan',
	['thenetherlands'] = 'netherlands',
	['tristan'] = 'tristandacunha',
	['usca'] = 'northamerica',
	['unasur'] = 'southamerica',
	['unitedstatesofamerica'] = 'unitedstates',
	['holysee'] = 'vaticancity',
	['vatican'] = 'vaticancity',
	['virginislands'] = 'virginislands(british)',
	['britishvirginislands'] = 'virginislands(british)',
	['u.s.virginislands'] = 'virginislands(u.s.)',
	['unitedstatesvirginislands'] = 'virginislands(u.s.)',
	['u.s.minoroutlyingislands'] = 'unitedstatesminoroutlyingislands',
	['oce'] = 'oceania',
	['australia/newzealand'] = 'oceania',
	['global'] = 'world',
	--needed due to lpdb length restrictions
	--for inside matches --> max length 20
	--minus the spaces in cut of the flag names
	['southgeorgiaandth'] = 'southgeorgiaandthesouthsandwichislands',
	['bosniaandherzegovi'] = 'bosniaandherzegovina',
	--for inside player --> max length 40
	--minus the spaces in cut of the flag names
	['southgeorgiaandthesouthsandwichisl'] = 'southgeorgiaandthesouthsandwichislands',

	--uk flags
	['ukwa'] = 'wales',
	['uksc'] = 'scotland',
	['uken'] = 'england',
	['ukni'] = 'northernireland',

	--language flag abbreviations
	['usuk'] = 'englishspeaking',
	['deat'] = 'germanspeaking',
	['esmx'] = 'spanishspeaking',
	['ptbr'] = 'portuguesespeaking',
	['ruby'] = 'russianspeaking',

	--language flag aliases
	['engspeaking'] = 'englishspeaking',
	['gerspeaking'] = 'germanspeaking',

	['ff'] = 'filler',
	['fillerflag'] = 'filler',
	['unknown'] = 'filler',

	['nonrepresenting'] = 'non-representing',
	['non'] = 'non-representing',
	['none'] = 'non-representing',
}

-- This table includes
-- ISO 639-1 (language iso) values
-- for languages that have a special flag
local languageTwoLetter = {
	--language flag abbreviations
	['en'] = 'englishspeaking',
	['de'] = 'germanspeaking',
	['es'] = 'spanishspeaking',
	['pt'] = 'portuguesespeaking',
	['ru'] = 'russianspeaking',
}

-- This table includes
-- ISO 639-2/T (language iso) values
-- for languages that have a special flag
local languageThreeLetter = {
	--language flag abbreviations
	['eng'] = 'englishspeaking',
	['deu'] = 'germanspeaking',
	['spa'] = 'spanishspeaking',
	['por'] = 'portuguesespeaking',
	['rus'] = 'russianspeaking',
}

-- This table includes
-- ISO 3166-2 to the ISO 3166-1 country, that fulfill
-- https://liquipedia.net/commons/Liquipedia:Flag_and_Country_Policy#Countries
local iso31662 = {
	['wales'] = 'unitedkingdom',
	['scotland'] = 'unitedkingdom',
	['england'] = 'unitedkingdom',
	['northernireland'] = 'unitedkingdom',
}

return {
	data = data,
	twoLetter = twoLetter,
	threeLetter = threeLetter,
	aliases = aliases,
	languageTwoLetter = languageTwoLetter,
	languageThreeLetter = languageThreeLetter,
	iso31662 = iso31662,
}
