---
-- @Liquipedia
-- page=Module:Components/Html
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

local Lua = require('Module:Lua')
local ComponentCore = Lua.import('Module:Components/Component')

local Html = {}

Html.Abbr = ComponentCore.tag('abbr')
Html.Aside = ComponentCore.tag('aside')
Html.B = ComponentCore.tag('b')
Html.Bdi = ComponentCore.tag('bdi')
Html.Bdo = ComponentCore.tag('bdo')
Html.Big = ComponentCore.tag('big')
Html.Blockquote = ComponentCore.tag('blockquote')
Html.Br = ComponentCore.tag('br')
Html.Caption = ComponentCore.tag('caption')
Html.Center = ComponentCore.tag('center')
Html.Cite = ComponentCore.tag('cite')
Html.Code = ComponentCore.tag('code')
Html.Col = ComponentCore.tag('col')
Html.Colgroup = ComponentCore.tag('colgroup')
Html.Data = ComponentCore.tag('data')
Html.Dd = ComponentCore.tag('dd')
Html.Del = ComponentCore.tag('del')
Html.Dfn = ComponentCore.tag('dfn')
Html.Div = ComponentCore.tag('div')
Html.Dl = ComponentCore.tag('dl')
Html.Dt = ComponentCore.tag('dt')
Html.Em = ComponentCore.tag('em')
Html.Figcaption = ComponentCore.tag('figcaption')
Html.Figure = ComponentCore.tag('figure')
Html.Font = ComponentCore.tag('font')
Html.Fragment = ComponentCore.tag('fragment')
Html.H1 = ComponentCore.tag('h1')
Html.H2 = ComponentCore.tag('h2')
Html.H3 = ComponentCore.tag('h3')
Html.H4 = ComponentCore.tag('h4')
Html.H5 = ComponentCore.tag('h5')
Html.H6 = ComponentCore.tag('h6')
Html.Hr = ComponentCore.tag('hr')
Html.I = ComponentCore.tag('i')
Html.Ins = ComponentCore.tag('ins')
Html.Kbd = ComponentCore.tag('kbd')
Html.Li = ComponentCore.tag('li')
Html.Mark = ComponentCore.tag('mark')
Html.Ol = ComponentCore.tag('ol')
Html.P = ComponentCore.tag('p')
Html.Pre = ComponentCore.tag('pre')
Html.Q = ComponentCore.tag('q')
Html.S = ComponentCore.tag('s')
Html.Samp = ComponentCore.tag('samp')
Html.Small = ComponentCore.tag('small')
Html.Span = ComponentCore.tag('span')
Html.Strike = ComponentCore.tag('strike')
Html.Strong = ComponentCore.tag('strong')
Html.Sub = ComponentCore.tag('sub')
Html.Sup = ComponentCore.tag('sup')
Html.Table = ComponentCore.tag('table')
Html.Tbody = ComponentCore.tag('tbody')
Html.Td = ComponentCore.tag('td')
Html.Tfoot = ComponentCore.tag('tfoot')
Html.Th = ComponentCore.tag('th')
Html.Thead = ComponentCore.tag('thead')
Html.Time = ComponentCore.tag('time')
Html.Tr = ComponentCore.tag('tr')
Html.Tt = ComponentCore.tag('tt')
Html.U = ComponentCore.tag('u')
Html.Ul = ComponentCore.tag('ul')
Html.Var = ComponentCore.tag('var')
Html.Wbr = ComponentCore.tag('wbr')

return Html
