return {
	['text'] = {
		['1']            =    'F1',
		['2']            =    'F2',
		['3']            =    'F3',
		['4']            =    'Regional',
		['5']            =    'F4',
		['6']            =    'Karts',
		['Monthly']      =    'Monthly',
		['Weekly']       =    'Weekly',
		['Qualifier']    =    'Qualifier',
		['Misc']         =    'Misc',
		['Show Match']   =    'Show Match',
		['']             =    'Undefined',
		tiers = {
			['1']            =    'F1',
			['2']            =    'F2',
			['3']            =    'F3',
			['4']            =    'Regional',
			['5']            =    'F4',
			['6']            =    'Karts',
			['monthly']      =    'Monthly',
			['weekly']       =    'Weekly',
			['qualifier']    =    'Qualifier',
			['misc']         =    'Misc',
			['show match']   =    'Show Match',
			['']             =    'Undefined',
		},
		types = {
			['monthly']      =    'Monthly',
			['weekly']       =    'Weekly',
			['qualifier']    =    'Qualifier',
			['misc']         =    'Misc',
			['show match']   =    'Show Match',
		},
	},
	['display'] = {
		['1']            =    '<span style="display:none;">A1</span>[[Formula 1 Tournaments|F1]]',
		['2']            =    '<span style="display:none;">A2</span>[[Formula 2 Tournaments|F2]]',
		['3']            =    '<span style="display:none;">A3</span>[[Formula 3 Tournaments|F3]]',
		['4']            =    '<span style="display:none;">A4</span>[[Formula Regional Tournaments|Regional]]',
		['5']            =    '<span style="display:none;">A4</span>[[Formula 4 Tournaments|F4]]',
		['6']            =    '<span style="display:none;">A5</span>[[Karting Tournaments|Karts]]',
		['Monthly']      =    '<span style="display:none;">A6</span>[[Monthly Tournaments|Monthly]]',
		['Weekly']       =    '<span style="display:none;">A7</span>[[Weekly Tournaments|Weekly]]',
		['Qualifier']    =    '<span style="display:none;">A8</span>[[Qualifier Tournaments|Qualifier]]',
		['Misc']         =    '<span style="display:none;">A9</span>[[Miscellaneous Tournaments|Misc]]',
		['Show Match']   =    '<span style="display:none;">B1</span>[[Show Matches|Show&nbsp;M.]]',
		['']             =    '<span style="display:none;">B2</span>Undefined',
	},
	['number'] = {
		['F1']       =    '1',
		['F2']       =    '2',
		['F3']       =    '3',
		['Regional']       =    '4',
		['F4']       =    '5',
		['Karts']       =    '6',
		['Monthly']      =    'Monthly',
		['Weekly']       =    'Weekly',
		['Qualifier']    =    'Qualifier',
		['Misc']         =    'Misc',
		['Show Match']   =    'Show Match',
		['']             =    '',
	}
}
