---
-- @Liquipedia
-- page=Module:EwcTeamsOverview/data
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

return {
	EWC2025 = {
		{lis = 'apex', wiki = 'apexlegends'},
		{lis = 'cf', wiki = 'crossfire'},
		{lis = 'chess', wiki = 'chess'},
		{lis = 'codbo6', wiki = 'callofduty'},
		{lis = 'codwz', wiki = 'callofduty'},
		{lis = 'cs2', wiki = 'counterstrike'},
		{lis = 'dota2', wiki = 'dota2'},
		{lis = 'fc25', wiki = 'easportsfc'},
		{lis = 'ff', wiki = 'freefire'},
		{lis = 'ffcotw', wiki = 'fighters'},
		{lis = 'hok', wiki = 'honorofkings'},
		{lis = 'lol', wiki = 'leagueoflegends'},
		{lis = 'mlbb', wiki = 'mobilelegends'},
		{lis = 'mwi', wiki = 'mobilelegends'},
		{lis = 'ow2', wiki = 'overwatch'},
		{lis = 'pubg', wiki = 'pubg'},
		{lis = 'pubgm', wiki = 'pubgmobile'},
		{lis = 'r6s', wiki = 'rainbowsix'},
		{lis = 'rennsport', wiki = 'simracing'},
		{lis = 'rl', wiki = 'rocketleague'},
		{lis = 'sc2', wiki = 'starcraft2'},
		{lis = 'sf6', wiki = 'fighters'},
		{lis = 't8', wiki = 'fighters'},
		{lis = 'tft', wiki = 'tft'},
		{lis = 'valorant', wiki = 'valorant'},
	},
	EWC2026 = {
		{lis = 'apex', wiki = 'apexlegends'},
		{lis = 'cf', wiki = 'crossfire'},
		{lis = 'chess', wiki = 'chess'},
		{lis = 'codbo7', wiki = 'callofduty'},
		{lis = 'codwz', wiki = 'callofduty'},
		{lis = 'cs2', wiki = 'counterstrike'},
		{lis = 'dota2', wiki = 'dota2'},
		{lis = 'fc26', wiki = 'easportsfc'},
		{lis = 'ff', wiki = 'freefire'},
		{lis = 'ffcotw', wiki = 'fighters'},
		{lis = 'fortnite', wiki = 'fortnite'},
		{lis = 'hok', wiki = 'honorofkings'},
		{lis = 'lol', wiki = 'leagueoflegends'},
		{lis = 'mlbb', wiki = 'mobilelegends'},
		{lis = 'mwi', wiki = 'mobilelegends'},
		{lis = 'ow2', wiki = 'overwatch'},
		{lis = 'pubg', wiki = 'pubg'},
		{lis = 'pubgm', wiki = 'pubgmobile'},
		{lis = 'r6s', wiki = 'rainbowsix'},
		{lis = 'rl', wiki = 'rocketleague'},
		{lis = 'sf6', wiki = 'fighters'},
		{lis = 't8', wiki = 'fighters'},
		{lis = 'tft', wiki = 'tft'},
		{lis = 'tm', wiki = 'trackmania'},
		{lis = 'valorant', wiki = 'valorant'},
	},
	ENC2026 = {
		{lis = 'apex', wiki = 'apexlegends'},
		{lis = 'chess', wiki = 'chess'},
		{lis = 'cs2', wiki = 'counterstrike'},
		{lis = 'dota2', wiki = 'dota2'},
		{lis = 'fc26', wiki = 'easportsfc'},
		{lis = 'ffcotw', wiki = 'fighters'},
		{lis = 'hok', wiki = 'honorofkings'},
		{lis = 'lol', wiki = 'leagueoflegends'},
		{lis = 'mlbb', wiki = 'mobilelegends'},
		{lis = 'pubg', wiki = 'pubg'},
		{lis = 'pubgm', wiki = 'pubgmobile'},
		{lis = 'r6s', wiki = 'rainbowsix'},
		{lis = 'rl', wiki = 'rocketleague'},
		{lis = 'sf6', wiki = 'fighters'},
		{lis = 'tm', wiki = 'trackmania'},
		{lis = 'valorant', wiki = 'valorant'},
	}
}
