#!/bin/bash

cd /home/hjpalpha

pwb replace -lang:starcraft -transcludes:"LegacyMatchList" -transcludes:"LegacyBracket" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyMatchList" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp" "\{\{[mM]atchMaps/Legacy" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=preprocess" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=BracketMatchSummary|fn=draw|generate=true" "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp"

#pwb replace -lang:starcraft2 -transcludes:"Legacy Match list start" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacy Match list start(.*?)\}\}\s*\n*\s*\{\{[mM]atch maps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=preprocess|dev=hjp|generate=true" "\{\{[mM]atch maps" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=preprocess|dev=hjp|generate=true" "\{\{[mM]atch list end\|?\}\}" "}}"

#pwb replace -lang:warcraft -transcludes:"LegacyMatchList" -transcludes:"LegacyMatchListStart" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*(\|?)\{\{" "{{subst:#invoke:Lua|invoke|module=LegacyMatchMaps|fn=generateTeam|dev=hjp\1\n\2{{" "\{\{[bB]racketTeamMatchMulti" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/ConvertMapData|fn=teamMulti" "\{\{[bB]racketTeamMatch([^M])" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/ConvertMapData|fn=team\1" "\{\{[gG]roupMatchSummary" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[mM]atchMaps([^T])" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs\1" "\{\{[lL]egacyMatchList([^S])" "{{subst:#invoke:Lua|invoke|module=LegacyMatchMaps|fn=generateSolo|dev=hjp\1" "\{\{[mM]atchListEnd\|?\}\}" "}}" "\{\{[mM]atchMapsTeams" "|{{subst:#invoke:Lua|invoke|module=LegacyMatchMaps|fn=teamMatch|dev=hjp|generate=true"

#pwb replace -lang:leagueoflegends -transcludes:"LegacyMatchListStart" -transcludes:"LegacyBracket" -summary:"Convert LegacyBrackets to Brackets" -pt:60 -regex -always -dotall "\{\{LegacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummaryL?u?a?" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertBracketMatchSummary|dev=hjp" "\{\{[mM]atchLua" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[mM]atch/old" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMapsL?u?a?" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|dev=hjp|fn=generate2\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|dev=hjp|fn=convertMatch|generate=true" "\{\{[mM]atchMapsL?u?a?" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|dev=hjp|fn=convertMatch|generate=true" "\{\{MatchListEnd\|?\}\}" "}}"

#pwb replace -lang:rainbowsix -transcludes:"LegacyMatchListStart" -transcludes:"LegacyBracket" -transcludes:"LegacySingleMatch" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[Mm]apVetoTableSmall" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=LegacyBracketMatchSummary|fn=convert" "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy/Store|dev=hjp|fn=generate2\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=main|dev=hjp|generate=true" "\{\{[Mm]atchMaps" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=main|dev=hjp|generate=true" "\{\{[Mm]atchListEnd\|?\}\}" "}}" "\{\{[lL]egacySingleMatch" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy/Store|fn=generateSingleMatch|dev=hjp" "\{\{LegacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp"

pwb replace -lang:overwatch -transcludes:"LegacyBracket" -transcludes:"LegacyMatchList" -transcludes:"LegacyMatchListStart" -transcludes:"LegacySingleMatch" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertBracketMatchSummary|dev=hjp" "\{\{[lL]egacyMatchList([^S])" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1" "\{\{[lL]egacySingleMatch" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generateSingleMatch|dev=hjp" "=[\s\n]*\{\{[mM]atchMaps" "={{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate2|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\}\}([\s\n]*)\{\{[mM]atchMaps" "}}\1|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[mM]atchListEnd\|?\}\}" "}}"

pwb replace -lang:valorant -transcludes:"LegacySingleMatch" -transcludes:"LegacyBracket" -transcludes:"LegacyMatchListStart" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[mM]apVetoTableSmall" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMapVeto|dev=hjp" "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[lL]egacySingleMatch" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generateSingleMatch|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertBracketMatchSummary|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[mM]atchMaps" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|dev=hjp|generate=true" "\{\{MatchListEnd\|?\}\}" "}}"

pwb replace -lang:callofduty -transcludes:"LegacyBracket" -transcludes:"LegacyMatchListStart" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=LegacyBracketMatchSummary|fn=run" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=match|generate=true|dev=hjp" "\{\{[mM]atchMaps" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=match|dev=hjp|generate=true" "\{\{MatchListEnd\|?\}\}" "}}"

pwb replace -lang:heroes -transcludes:"LegacyMatchList" -transcludes:"LegacyBracket" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertBracketMatchSummary|dev=hjp" "\{\{[mM]atch/old" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMap|dev=hjp" "\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|dev=hjp" "\{\{[lL]egacyMatchList" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp"

pwb replace -lang:arenafps -transcludes:"LegacyBracket" -transcludes:"LegacyMatchList" -transcludes:"LegacySingleMatch" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[mM]atchMaps" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=LegacyBracketMatchSummary|fn=convert" "\{\{[lL]egacySingleMatch" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generateSingleMatch|dev=hjp" "\{\{[lL]egacyMatchList" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp"

pwb replace -lang:hearthstone -transcludes:"LegacyBracket" -transcludes:"LegacyMatchListStart" -transcludes:"LegacyMatchList"-summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[lL]egacyMatchList([^S])" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1" "\{\{[mM]atchMaps([^N])" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[mM]atchListEnd\|?\}\}" "}}" "\{\{[bB] " "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[bB]racketMatchSummaryNew" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[mM]atchMapsNew" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMapsNew" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate2|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|generate=true|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\|\{\{subst" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate2|dev=hjp\1\n|{{subst"

pwb replace -lang:ageofempires -transcludes:MatchSection -summary:"Prep to convert LegacyMatch2 wrappers" -pt:60 -regex -always "\{\{\s*[mM]atchSection\s*\|([^\}]*)\}\}\s*\n*\s*\{\{[mM]atch ?[mM]apsT?e?a?m?" "{{MatchMaps|matchsection=\1"

pwb replace -lang:ageofempires -transcludes:LegacySingleMatch -transcludes:LegacyBracket -transcludes: -transcludes:LegacyMatchListStart -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=LegacyBracketMatchSummary|fn=convert" "\{\{[mM]atchTeam" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[lL]egacySingleMatch" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generateSingleMatch|dev=hjp" "\{\{[mM]atchListEnd\|?\}\}" "}}" "\{\{[mM]atch list end\|?\}\}" "}}" "\{\{[mM]atch ?[mM]apsT?e?a?m?" "|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|dev=hjp|generate=true" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*(<\!\-\-.*?\-\->)?\s*\n*\s*\{\{[mM]atch ?[mM]apsT?e?a?m?" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=convertMatch|dev=hjp|generate=true" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*(<\!\-\-.*?\-\->)?\s*\n*\s*\|\{\{subst" "{{subst:#invoke:Lua|invoke|module=MatchMaps/Legacy|fn=generate|dev=hjp\1\n|{{subst"

pwb replace -lang:battalion -transcludes:"LegacyBracket" -transcludes:"LegacyMatchListStart" -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall "\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp" "\{\{[bB]racketMatchSummary" "{{subst:#invoke:Lua|invoke|module=Json|fn=fromArgs" "\{\{[Mm]atchListEnd\|?\}\}" "}}" "\{\{[mM]atchMaps" "|{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/MatchList|fn=matchMaps|generate=true|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\{\{[mM]atchMapsNew" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/MatchList|fn=generate|dev=hjp\1\n|{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/MatchList|fn=matchMaps|generate=true|dev=hjp" "\{\{[lL]egacyMatchListStart(.*?)\}\}\s*\n*\s*\|\{\{subst" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/MatchList|fn=generate|dev=hjp\1\n|{{subst"







"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""
"" ""







"\{\{[lL]egacyBracket" "{{subst:#invoke:Lua|invoke|module=MatchGroup/Legacy/Default|fn=runGenerate|dev=hjp"

pwb replace -lang:.... -page:"...." -summary:"Convert LegacyMatch2 wrappers" -pt:60 -regex -always -dotall
