---
-- @Liquipedia
-- page=Module:Faction/Data
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

local Lua = require('Module:Lua')

local Array = Lua.import('Module:Array')

local AOE1_SUFFIX = '/Age of Empires I'
local AOE2_SUFFIX = '/Age of Empires II'
local AOE3_SUFFIX = '/Age of Empires III'
local AOE4_SUFFIX = '/Age of Empires IV'
local AOM_SUFFIX = '/Age of Mythology'
local AOEO_SUFFIX = '/Age of Empires Online'

local factionPropsAoE1 = {
	assyrians = {
		index = 1,
		name = 'Assyrians',
		faction = 'assyrians',
	},
	babylonians = {
		index = 2,
		name = 'Babylonians',
		pageName = 'Babylonians' .. AOE1_SUFFIX,
		faction = 'babylonians',
	},
	carthaginians = {
		index = 3,
		name = 'Carthaginians',
		faction = 'carthaginians',
	},
	choson = {
		index = 4,
		name = 'Choson',
		faction = 'choson',
	},
	egyptians = {
		index = 5,
		name = 'Egyptians',
		pageName = 'Egyptians' .. AOE1_SUFFIX,
		faction = 'egyptians',
	},
	greeks = {
		index = 6,
		name = 'Greeks',
		pageName = 'Greeks' .. AOE1_SUFFIX,
		faction = 'greeks',
	},
	hittites = {
		index = 7,
		name = 'Hittites',
		faction = 'hittites',
	},
	macedonians = {
		index = 8,
		name = 'Macedonians',
		faction = 'macedonians',
	},
	minoans = {
		index = 9,
		name = 'Minoans',
		faction = 'minoans',
	},
	palmyrans = {
		index = 10,
		name = 'Palmyrans',
		faction = 'palmyrans',
	},
	persians = {
		index = 11,
		name = 'Persians',
		pageName = 'Persians' .. AOE1_SUFFIX,
		faction = 'persians',
	},
	phoenicians = {
		index = 12,
		name = 'Phoenicians',
		faction = 'phoenicians',
	},
	romans = {
		index = 13,
		name = 'Romans',
		pageName = 'Romans' .. AOE1_SUFFIX,
		faction = 'romans',
	},
	shang = {
		index = 14,
		name = 'Shang',
		faction = 'shang',
	},
	sumerians = {
		index = 15,
		name = 'Sumerians',
		faction = 'sumerians',
	},
	yamato = {
		index = 16,
		name = 'Yamato',
		faction = 'yamato',
	},
	lacviet = {
		index = 17,
		name = 'Lac Viet',
		faction = 'lacviet',
	},

	unknown = {
		index = 18,
		name = 'Unknown',
		faction = 'unknown',
	},
}

local factionPropsAoE2 = {
	achaemenids = {
		index = 1,
		name = 'Achaemenids',
		faction = 'achaemenids',
	},
	armenians = {
		index = 2,
		name = 'Armenians',
		faction = 'armenians',
	},
	athenians = {
		index = 3,
		name = 'Athenians',
		faction = 'athenians',
	},
	aztecs = {
		index = 4,
		name = 'Aztecs',
		pageName = 'Aztecs' .. AOE2_SUFFIX,
		faction = 'aztecs',
	},
	berbers = {
		index = 5,
		name = 'Berbers',
		faction = 'berbers',
	},
	bengalis = {
		index = 6,
		name = 'Bengalis',
		faction = 'bengalis',
	},
	bohemians = {
		index = 7,
		name = 'Bohemians',
		faction = 'bohemians',
	},
	britons = {
		index = 8,
		name = 'Britons',
		faction = 'britons',
	},
	bulgarians = {
		index = 9,
		name = 'Bulgarians',
		faction = 'bulgarians',
	},
	burgundians = {
		index = 10,
		name = 'Burgundians',
		faction = 'burgundians',
	},
	burmese = {
		index = 11,
		name = 'Burmese',
		faction = 'burmese',
	},
	byzantines = {
		index = 12,
		name = 'Byzantines',
		pageName = 'Byzantines'  .. AOE2_SUFFIX,
		faction = 'byzantines',
	},
	celts = {
		index = 13,
		name = 'Celts',
		pageName = 'Celts' .. AOE2_SUFFIX,
		faction = 'celts',
	},
	chinese = {
		index = 14,
		name = 'Chinese',
		pageName = 'Chinese' .. AOE2_SUFFIX,
		faction = 'chinese',
	},
	cumans = {
		index = 15,
		name = 'Cumans',
		faction = 'cumans',
	},
	dravidians = {
		index = 16,
		name = 'Dravidians',
		faction = 'dravidians',
	},
	ethiopians = {
		index = 17,
		name = 'Ethiopians',
		pageName = 'Ethiopians' .. AOE2_SUFFIX,
		faction = 'ethiopians',
	},
	franks = {
		index = 18,
		name = 'Franks',
		faction = 'franks',
	},
	georgians = {
		index = 19,
		name = 'Georgians',
		faction = 'georgians',
	},
	goths = {
		index = 20,
		name = 'Goths',
		faction = 'goths',
	},
	gurjaras = {
		index = 21,
		name = 'Gurjaras',
		faction = 'gurjaras',
	},
	hindustanis = {
		index = 22,
		name = 'Hindustanis',
		faction = 'hindustanis',
	},
	huns = {
		index = 23,
		name = 'Huns',
		faction = 'huns',
	},
	inca = {
		index = 24,
		name = 'Inca',
		faction = 'inca',
	},
	indians = {
		index = 25,
		name = 'Indians',
		pageName = 'Indians' .. AOE2_SUFFIX .. '/The_Forgotten',
		faction = 'indians',
	},
	italians = {
		index = 26,
		name = 'Italians',
		pageName = 'Italians' .. AOE2_SUFFIX,
		faction = 'italians',
	},
	japanese = {
		index = 27,
		name = 'Japanese',
		pageName = 'Japanese' .. AOE2_SUFFIX,
		faction = 'japanese',
	},
	jurchens = {
		index = 28,
		name = 'Jurchens',
		faction = 'jurchens',
	},
	khitans = {
		index = 29,
		name = 'Khitans',
		faction = 'khitans',
	},
	khmer = {
		index = 30,
		name = 'Khmer',
		faction = 'khmer',
	},
	koreans = {
		index = 31,
		name = 'Koreans',
		faction = 'koreans',
	},
	lithuanians = {
		index = 32,
		name = 'Lithuanians',
		faction = 'lithuanians',
	},
	macedonians = {
		index = 33,
		name = 'Macedonians',
		faction = 'macedonians',
	},	
	magyars = {
		index = 34,
		name = 'Magyars',
		faction = 'magyars',
	},
	malay = {
		index = 35,
		name = 'Malay',
		faction = 'malay',
	},
	malians = {
		index = 36,
		name = 'Malians',
		pageName = 'Malians' .. AOE2_SUFFIX,
		faction = 'malians',
	},
	maya = {
		index = 37,
		name = 'Maya',
		faction = 'maya',
	},
	mongols = {
		index = 38,
		name = 'Mongols',
		pageName = 'Mongols' .. AOE2_SUFFIX,
		faction = 'mongols',
	},
	persians = {
		index = 39,
		name = 'Persians',
		pageName = 'Persians' .. AOE2_SUFFIX,
		faction = 'persians',
	},
	poles = {
		index = 40,
		name = 'Poles',
		faction = 'poles',
	},
	portuguese = {
		index = 41,
		name = 'Portuguese',
		pageName = 'Portuguese' .. AOE2_SUFFIX,
		faction = 'portuguese',
	},
	puru = {
		index = 42,
		name = 'Puru',
		faction = 'puru',
	},
	romans = {
		index = 43,
		name = 'Romans',
		pageName = 'Romans' .. AOE2_SUFFIX,
		faction = 'romans',
	},
	saracens = {
		index = 44,
		name = 'Saracens',
		faction = 'saracens',
	},
	shu = {
		index = 45,
		name = 'Shu',
		faction = 'shu',
	},
	sicilians = {
		index = 46,
		name = 'Sicilians',
		faction = 'sicilians',
	},
	slavs = {
		index = 47,
		name = 'Slavs',
		faction = 'slavs',
	},
	spanish = {
		index = 48,
		name = 'Spanish',
		pageName = 'Spanish' .. AOE2_SUFFIX,
		faction = 'spanish',
	},
	spartans = {
		index = 49,
		name = 'Spartans',
		faction = 'spartans',
	},
	tatars = {
		index = 50,
		name = 'Tatars',
		faction = 'tatars',
	},
	teutons = {
		index = 51,
		name = 'Teutons',
		faction = 'teutons',
	},
		thracians = {
		index = 52,
		name = 'Thracians',
		faction = 'thracians',
	},
	turks = {
		index = 53,
		name = 'Turks',
		faction = 'turks',
	},
	vietnamese = {
		index = 54,
		name = 'Vietnamese',
		faction = 'vietnamese',
	},
	vikings = {
		index = 55,
		name = 'Vikings',
		pageName = 'Vikings' .. AOE2_SUFFIX,
		faction = 'vikings',
	},
	wei = {
		index = 56,
		name = 'Wei',
		faction = 'wei',
	},
	wu = {
		index = 57,
		name = 'Wu',
		faction = 'wu',
	},
	unknown = {
		index = 58,
		name = 'Unknown',
		faction = 'unknown',
	},
}

local factionPropsAoE3 = {
	aztecs = {
		index = 1,
		name = 'Aztecs',
		pageName = 'Aztecs' .. AOE3_SUFFIX,
		faction = 'aztecs',
	},
	british = {
		index = 2,
		name = 'British',
		faction = 'british',
	},
	chinese = {
		index = 3,
		name = 'Chinese',
		pageName = 'Chinese' .. AOE3_SUFFIX,
		faction = 'chinese',
	},
	dutch = {
		index = 4,
		name = 'Dutch',
		faction = 'dutch',
	},
	ethiopians = {
		index = 5,
		name = 'Ethiopians',
		pageName = 'Ethiopians' .. AOE3_SUFFIX,
		faction = 'ethiopians',
	},
	french = {
		index = 6,
		name = 'French',
		pageName = 'French' .. AOE3_SUFFIX,
		faction = 'french',
	},
	germans = {
		index = 7,
		name = 'Germans',
		faction = 'germans',
	},
	haudenosaunee = {
		index = 8,
		name = 'Haudenosaunee',
		faction = 'haudenosaunee',
	},
	hausa = {
		index = 9,
		name = 'Hausa',
		faction = 'hausa',
	},
	incas = {
		index = 10,
		name = 'Incas',
		pageName = 'Incas' .. AOE3_SUFFIX,
		faction = 'incas',
	},
	indians = {
		index = 11,
		name = 'Indians',
		pageName = 'Indians' .. AOE3_SUFFIX,
		faction = 'indians',
	},
	italians = {
		index = 12,
		name = 'Italians',
		pageName = 'Italians' .. AOE3_SUFFIX,
		faction = 'italians',
	},
	japanese = {
		index = 13,
		name = 'Japanese',
		pageName = 'Japanese' .. AOE3_SUFFIX,
		faction = 'japanese',
	},
	lakota = {
		index = 14,
		name = 'Lakota',
		faction = 'lakota',
	},
	maltese = {
		index = 15,
		name = 'Maltese',
		pageName = 'Maltese' .. AOE3_SUFFIX,
		faction = 'maltese',
	},
	mexicans = {
		index = 16,
		name = 'Mexicans',
		faction = 'mexicans',
	},
	ottomans = {
		index = 17,
		name = 'Ottomans',
		pageName = 'Ottomans' .. AOE3_SUFFIX,
		faction = 'ottomans',
	},
	portuguese = {
		index = 18,
		name = 'Portuguese',
		pageName = 'Portuguese' .. AOE3_SUFFIX,
		faction = 'portuguese',
	},
	russians = {
		index = 19,
		name = 'Russians',
		faction = 'russians',
	},
	spanish = {
		index = 20,
		name = 'Spanish',
		pageName = 'Spanish' .. AOE3_SUFFIX,
		faction = 'spanish',
	},
	swedes = {
		index = 21,
		name = 'Swedes',
		faction = 'swedes',
	},
	unitedstates = {
		index = 22,
		name = 'United States',
		faction = 'unitedstates',
	},
	random = {
		index = 23,
		name = 'Random',
		faction = 'random',
	},

	unknown = {
		index = 24,
		name = 'Unknown',
		faction = 'unknown',
	},
}

local factionPropsAoE4 = {
	abbasiddynasty = {
		index = 1,
		name = 'Abbasid Dynasty',
		faction = 'abbasiddynasty',
	},
	ayyubids = {
		index = 2,
		name = 'Ayyubids',
		faction = 'ayyubids',
	},
	byzantines = {
		index = 3,
		name = 'Byzantines',
		pageName = 'Byzantines' .. AOE4_SUFFIX,
		faction = 'byzantines',
	},
	chinese = {
		index = 4,
		name = 'Chinese',
		pageName = 'Chinese' .. AOE4_SUFFIX,
		faction = 'chinese',
	},
	delhisultanate = {
		index = 5,
		name = 'Delhi Sultanate',
		faction = 'delhisultanate',
	},
	english = {
		index = 6,
		name = 'English',
		faction = 'english',
	},
	french = {
		index = 7,
		name = 'French',
		pageName = 'French' .. AOE4_SUFFIX,
		faction = 'french',
	},
	goldenhorde = {
		index = 8,
		name = 'Golden Horde',
		faction = 'goldenhorde',
	},
	holyromanempire = {
		index = 9,
		name = 'Holy Roman Empire',
		faction = 'holyromanempire',
	},
	houseoflancaster = {
		index = 10,
		name = 'House of Lancaster',
		faction = 'houseoflancaster',
	},
	japanese = {
		index = 11,
		name = 'Japanese',
		pageName = 'Japanese' .. AOE4_SUFFIX,
		faction = 'japanese',
	},
	jeannedarc = {
		index = 12,
		name = 'Jeanne d\'Arc',
		faction = 'jeannedarc',
	},
	knightstemplar = {
		index = 13,
		name = 'Knights Templar',
		faction = 'knightstemplar',
	},
	macedoniandynasty = {
		index = 14,
		name = 'Macedonian Dynasty',
		faction = 'macedoniandynasty',
	},
	malians = {
		index = 15,
		name = 'Malians',
		pageName = 'Malians' .. AOE4_SUFFIX,
		faction = 'malians',
	},
	mongols = {
		index = 16,
		name = 'Mongols',
		pageName = 'Mongols' .. AOE4_SUFFIX,
		faction = 'mongols',
	},
	ottomans = {
		index = 17,
		name = 'Ottomans',
		pageName = 'Ottomans' .. AOE4_SUFFIX,
		faction = 'ottomans',
	},
	orderofthedragon = {
		index = 18,
		name = 'Order of the Dragon',
		faction = 'orderofthedragon',
	},
	rus = {
		index = 19,
		name = 'Rus',
		faction = 'rus',
	},
	sengokudaimyo = {
		index = 20,
		name = 'Sengoku Daimyo',
		faction = 'sengokudaimyo',
	},
	tughlaqdynasty = {
		index = 21,
		name = 'Tughlaq Dynasty',
		faction = 'tughlaqdynasty',
	},
	zhuxislegacy = {
		index = 22,
		name = 'Zhu Xi\'s Legacy',
		faction = 'zhuxislegacy',
	},

	unknown = {
		index = 23,
		name = 'Unknown',
		faction = 'unknown',
	},
}

local factionPropsAoM = {
	atlanteans = {
		index = 1,
		name = 'Atlanteans',
		faction = 'atlanteans',
	},
	chinese = {
		index = 2,
		name = 'Chinese',
		pageName = 'Chinese' .. AOM_SUFFIX,
		faction = 'chinese',
	},
	egyptians = {
		index = 3,
		name = 'Egyptians',
		pageName = 'Egyptians' .. AOM_SUFFIX,
		faction = 'egyptians',
	},
	greeks = {
		index = 4,
		name = 'Greeks',
		pageName = 'Greeks' .. AOM_SUFFIX,
		faction = 'greeks',
	},
	japanese = {
		index = 5,
		name = 'Japanese',
		pageName = 'Japanese' .. AOM_SUFFIX,
		faction = 'japanese',
	},
	norse = {
		index = 6,
		name = 'Norse',
		pageName = 'Norse' .. AOM_SUFFIX,
		faction = 'norse',
	},
	amaterasu = {
		index = 7,
		name = 'Amaterasu',
		faction = 'amaterasu',
	},
	freyr = {
		index = 8,
		name = 'Freyr',
		faction = 'freyr',
	},
	fuxi = {
		index = 9,
		name = 'Fuxi',
		faction = 'fuxi',
	},
	gaia = {
		index = 10,
		name = 'Gaia',
		pageName = 'Gaia',
		faction = 'gaia',
	},
	hades = {
		index = 11,
		name = 'Hades',
		faction = 'hades',
	},
	isis = {
		index = 12,
		name = 'Isis',
		faction = 'isis',
	},
	kronos = {
		index = 13,
		name = 'Kronos',
		faction = 'kronos',
	},
	loki = {
		index = 14,
		name = 'Loki',
		faction = 'loki',
	},
	nuwa = {
		index = 15,
		name = 'Nüwa',
		faction = 'nuwa',
	},
	odin = {
		index = 16,
		name = 'Odin',
		faction = 'odin',
	},
	oranos = {
		index = 17,
		name = 'Oranos',
		faction = 'oranos',
	},
	poseidon = {
		index = 18,
		name = 'Poseidon',
		pageName = 'Poseidon (god)',
		faction = 'poseidon',
	},
	ra = {
		index = 19,
		name = 'Ra',
		pageName = 'Ra (god)',
		faction = 'ra',
	},
	set = {
		index = 20,
		name = 'Set',
		faction = 'set',
	},
	shennong = {
		index = 21,
		name = 'Shennong',
		faction = 'shennong',
	},
	susanoo = {
		index = 22,
		name = 'Susanoo',
		faction = 'susanoo',
	},
	thor = {
		index = 23,
		name = 'Thor',
		faction = 'thor',
	},
	tsukuyomi = {
		index = 24,
		name = 'Tsukuyomi',
		faction = 'tsukuyomi',
	},
	zeus = {
		index = 25,
		name = 'Zeus',
		faction = 'zeus',
	},
	quetzalcoatl = {
		index = 26,
		name = 'Quetzalcoatl',
		faction = 'quetzalcoatl',
	},
	huitzilopochtli = {
		index = 27,
		name = 'Huitzilopochtli',
		faction = 'huitzilopochtli',
	},
	tezcatlipoca = {
		index = 28,
		name = 'Tezcatlipoca',
		faction = 'tezcatlipoca',
	},

	unknown = {
		index = 29,
		name = 'Unknown',
		faction = 'unknown',
	},
}

local factionPropsAoEO = {
	babylonians = {
		index = 1,
		name = 'Babylonians',
		pageName = 'Babylonians' .. AOEO_SUFFIX,
		faction = 'babylonians',
	},
	celts = {
		index = 2,
		name = 'Celts',
		pageName = 'Celts' .. AOEO_SUFFIX,
		faction = 'celts',
	},
	egyptians = {
		index = 3,
		name = 'Egyptians',
		pageName = 'Egyptians' .. AOEO_SUFFIX,
		faction = 'egyptians',
	},
	greeks = {
		index = 4,
		name = 'Greeks',
		pageName = 'Greeks' .. AOEO_SUFFIX,
		faction = 'greeks',
	},
	indians = {
		index = 5,
		name = 'Indians',
		pageName = 'Indians' .. AOEO_SUFFIX,
		faction = 'indians',
	},
	norse = {
		index = 6,
		name = 'Norse',
		pageName = 'Norse' .. AOEO_SUFFIX,
		faction = 'norse',
	},
	persians = {
		index = 7,
		name = 'Persians',
		pageName = 'Persians' .. AOEO_SUFFIX,
		faction = 'persians',
	},
	romans = {
		index = 8,
		name = 'Romans',
		pageName = 'Romans' .. AOEO_SUFFIX,
		faction = 'romans',
	},

	unknown = {
		index = 9,
		name = 'Unknown',
		faction = 'unknown',
	},
}

return {
	factionProps = {
		aoe1 = factionPropsAoE1,
		aoe2 = factionPropsAoE2,
		aoe3 = factionPropsAoE3,
		aoe4 = factionPropsAoE4,
		aom = factionPropsAoM,
		aoeo = factionPropsAoEO,
	},
	defaultFaction = 'unknown',
	factions = {
		aoe1 = Array.extractKeys(factionPropsAoE1),
		aoe2 = Array.extractKeys(factionPropsAoE2),
		aoe3 = Array.extractKeys(factionPropsAoE3),
		aoe4 = Array.extractKeys(factionPropsAoE4),
		aom = Array.extractKeys(factionPropsAoM),
		aoeo = Array.extractKeys(factionPropsAoEO),
	},
	aliases = {
		aoe1 = {
			asr = 'assyrians',
			asy = 'assyrians',
			bab = 'babylonians',
			car = 'carthaginians',
			cho = 'choson',
			egy = 'egyptians',
			gre = 'greeks',
			hit = 'hittites',
			mac = 'macedonians',
			min = 'minoans',
			pal = 'palmyrans',
			per = 'persians',
			pho = 'phoenicians',
			rom = 'romans',
			sha = 'shang',
			sum = 'sumerians',
			yam = 'yamato',
			lac = 'lacviet',
			lv = 'lacviet',
			['lac viet'] = 'lacviet',
		 },
		aoe2 = {
			ach = 'achaemenids',
			arm = 'armenians',
			ath = 'athenians',
			azt = 'aztecs',
			ber = 'berbers',
			ben = 'bengalis',
			boh = 'bohemians',
			bri = 'britons',
			bul = 'bulgarians',
			brg = 'burgundians',
			bur = 'burmese',
			byz = 'byzantines',
			cel = 'celts',
			chi = 'chinese',
			cms = 'cumans',
			cum = 'cumans',
			dra = 'dravidians',
			eth = 'ethiopians',
			fra = 'franks',
			geo = 'georgians',
			got = 'goths',
			gur = 'gurjaras',
			hin = 'hindustanis',
			hun = 'huns',
			inc = 'inca',
			incas = 'inca',
			ind = 'indians',
			ita = 'italians',
			jap = 'japanese',
			jpn = 'japanese',
			jur = 'jurchens',
			khi = 'khitans',
			khm = 'khmer',
			kor = 'koreans',
			lit = 'lithuanians',
			mac = 'macedonians',
			mag = 'magyars',
			mly = 'malay',
			mal = 'malians',
			mli = 'malians',
			may = 'maya',
			mayans = 'maya',
			mon = 'mongols',
			per = 'persians',
			pol = 'poles',
			por = 'portuguese',
			pur = 'puru',
			rom = 'romans',
			sar = 'saracens',
			sic = 'sicilians',
			sla = 'slavs',
			spa = 'spanish',
			spr = 'spartans',
			tat = 'tatars',
			teu = 'teutons',
			thr = 'thracians',
			tur = 'turks',
			vie = 'vietnamese',
			vik = 'vikings',
		},
		aoe3 = {
			azt = 'aztecs',
			brt = 'british',
			bri = 'british',
			chi = 'chinese',
			dut = 'dutch',
			eth = 'ethiopians',
			fre = 'french',
			ger = 'germans',
			hau = 'haudenosaunee',
			hsa = 'hausa',
			inc = 'incas',
			ind = 'indians',
			ita = 'italians',
			jap = 'japanese',
			jpn = 'japanese',
			lak = 'lakota',
			mal = 'maltese',
			malta = 'maltese',
			mex = 'mexicans',
			otm = 'ottomans',
			ott = 'ottomans',
			por = 'portuguese',
			rus = 'russians',
			ran = 'random',
			spa = 'spanish',
			swe = 'swedes',
			usa = 'unitedstates',
		},
		aoe4 = {
			abb = 'abbasiddynasty',
			aba = 'abbasiddynasty',
			abba = 'abbasiddynasty',
			abbasid = 'abbasiddynasty',
			ayy = 'ayyubids',
			byz = 'byzantines',
			chi = 'chinese',
			del = 'delhisultanate',
			delhi = 'delhisultanate',
			eng = 'english',
			fre = 'french',
			goh = 'goldenhorde',
			gol = 'goldenhorde',
			hre = 'holyromanempire',
			hol = 'houseoflancaster',
			jap = 'japanese',
			jpn = 'japanese',
			jea = 'jeannedarc',
			arc = 'jeannedarc',
			knt = 'knightstemplar',
			mac = 'macedoniandynasty',
			mal = 'malians',
			mon = 'mongols',
			ord = 'orderofthedragon',
			dra = 'orderofthedragon',
			otm = 'ottomans',
			ott = 'ottomans',
			sen = 'sengokudaimyo',
			tug = 'tughlaqdynasty',
			zhu = 'zhuxislegacy',
		},
		aom = {
			ama = 'amaterasu',
			atl = 'atlanteans',
			chi = 'chinese',
			egy = 'egyptians',
			fre = 'freyr',
			fux = 'fuxi',
			['fu xi'] = 'fuxi',
			gai = 'gaia',
			gre = 'greeks',
			had = 'hades',
			isi = 'isis',
			jap = 'japanese',
			kro = 'kronos',
			lok = 'loki',
			nor = 'norse',
			['nu wa'] = 'nuwa',
			nuw = 'nuwa',
			odi = 'odin',
			ora = 'oranos',
			pos = 'poseidon',
			she = 'shennong',
			sus = 'susanoo',
			tho = 'thor',
			tsu = 'tsukuyomi',
			zeu = 'zeus',
			que = 'quetzalcoatl',
			hui = 'huitzilopochtli',
			tez = 'tezcatlipoca',
		},
		aoeo = {
			bab = 'babylonians',
			cel = 'celts',
			egy = 'egyptians',
			gre = 'greeks',
			ind = 'indians',
			nor = 'norse',
			per = 'persians',
			rom = 'romans',
		}
	},
}
