---
-- @Liquipedia
-- wiki=leagueoflegends
-- page=Module:Transfer/Data
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--
return {
    positionConvert = {
        top = 'Top',
        ['1'] = 'Top',

        jg = 'Jungle',
        jgl = 'Jungle',
        jng = 'Jungle',
        jungle = 'Jungle',
        jungler = 'Jungle',
        ['2'] = 'Jungler',

        mid = 'Middle',
        middle = 'Middle',
        ['3'] = 'Middle',

        ad = 'Bot',
        ['ad carry'] = 'Bot',
        adc = 'Bot',
        bot = 'Bot',
        bottom = 'Bot',
        ['4'] = 'Bot',

        sup = 'Support',
        supp = 'Support',
        support = 'Support',
        ['5'] = 'Support',

        fill = 'Fill',
        flex = 'Flex',
    },
    positionIcons = {
        top = '[[File:Top icon blue.png|16px|Top|link=]]',
        jungler = '[[File:Jungler icon blue.png|16px|Jungler|link=]]',
        middle = '[[File:Middle icon blue.png|16px|Middle|link=]]',
        bot = '[[File:Bottom icon blue.png|16px|Bot|link=]]',
        support = '[[File:Support icon blue.png|16px|Support|link=]]',
        fill = '[[File:Fill icon blue.png|16px|Fill|link=]]',
        flex = '[[File:Fill icon blue.png|16px|Flex|link=]]',

        ['bottom/middle'] = '[[File:Bottom icon blue.png|16px|Bottom|link=]][[File:Middle icon blue.png|16px|Middle|link=]]',
        ['mid/jungle'] = '[[File:Middle icon blue.png|16px|Middle|link=]][[File:Jungle icon blue.png|16px|Jungle|link=]]',
        ['support/bottom'] = '[[File:Support icon blue.png|16px|Support|link=]][[File:Bottom icon blue.png|16px|Bot|link=]]',
        ['support/bot'] = '[[File:Support icon blue.png|16px|Support|link=]][[File:Bottom icon blue.png|16px|Bot|link=]]',
        ['support/mid'] = '[[File:Support icon blue.png|16px|Support|link=]][[File:Middle icon blue.png|16px|Middle|link=]]',
        ['top/bot'] = '[[File:Top icon blue.png|16px|Top|link=]][[File:Bottom icon blue.png|16px|Bot|link=]]',
        ['top/jungle'] = '[[File:Top icon blue.png|16px|Top|link=]][[File:Jungler icon blue.png|16px|Jungler|link=]]',
        ['top/mid'] = '[[File:Top icon blue.png|16px|Top|link=]][[File:Middle icon blue.png|16px|Middle|link=]]',
        ['top/support'] = '[[File:Top icon blue.png|16px|Top|link=]][[File:Support icon blue.png|16px|Support|link=]]',

        top_substitute = '[[File:Substitute top icon.png|16px|Top (Substitute)|link=]]',
        jungler_substitute = '[[File:Substitute jungle icon.png|16px|Jungler (Substitute)|link=]]',
        middle_substitute = '[[File:Substitute mid icon.png|16px|Middle (Substitute)|link=]]',
        bot_substitute = '[[File:Substitute bot icon.png|16px|Bot (Substitute)|link=]]',
        support_substitute = '[[File:Substitute support icon.png|16px|Support (Substitute)|link=]]'
    },
    roleConvert = {
        ambassador = 'Ambassador',
        analyst = 'Analyst',
        ['data analyst'] = 'Data Analyst',
        ['assistant coach'] = 'Assistant Coach',
        coach = 'Coach',
        ['division coach'] = 'Division Coach',
        ['development coach'] = 'Development Coach',
        ['mental coach'] = 'Mental Coach',
        ['content creator'] = 'Content Creator',
        streamer = 'Streamer',
        ['head analyst'] = 'Head Analyst',
        ['assistant analyst'] = 'Assistant Analyst',
        ['head coach'] = 'Head Coach',
        ['general manager'] = 'General Manager',
        ['head manager'] = 'Head Manager',
        ['assistant manager'] = 'Assistant Manager',
        manager = 'Manager',
        ['performance manager'] = 'Performance Manager',
        ['performance coach'] = 'Performance Coach',
        ['position coach'] = 'Position Coach',
        ['positional coach'] = 'Positional Coach',
        ['sign language translator'] = 'Sign Language Translator',
        ['skill acquisition specialist'] = 'Skill Acquisition Specialist',
        staff = 'Staff',
        ['strategic coach'] = 'Strategic Coach',
        ['strategical coach'] = 'Strategical Coach',
        sub = 'Substitute',
        scout = 'Scout',
        ['talent scout'] = 'Talent Scout',
        substitute = 'Substitute',
        ['team director'] = 'Team Director',
        ['technical director'] = 'Technical Director',
        ['director of esports analytics'] = 'Director of Esports Analytics',
        coordinator = 'Coordinator',
        ['team manager'] = 'Team Manager',
        ['marketing manager'] = 'Marketing Manager',
        ['technical assistant'] = 'Technical Assistant',
        ['chief operating officer'] = 'Chief Operating Officer'
    },
    roleIcons = {
        ['head coach'] = '[[File:Head coach icon blue.png|16px|Head Coach|link=]]',
        coach = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Coach"><i class="fad fa-user-tie"></i></abbr></span>',
        ['mental coach'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Mental Coach"><i class="fad fa-user-tie"></i></abbr></span>',
        ['division coach'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Division Coach"><i class="fad fa-user-tie"></i></abbr></span>',
        ['development coach'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Development Coach"><i class="fad fa-user-tie"></i></abbr></span>',
        ['assistant coach'] = '[[File:Assistant coach icon blue.png|16px|Assistant Coach|link=]]',
        ['performance coach'] = '[[File:Positional coach icon blue.png|16px|Performance Coach|link=]]',
        ['position coach'] = '[[File:Positional coach icon blue.png|16px|Positional Coach|link=]]',
        ['positional coach'] = '[[File:Positional coach icon blue.png|16px|Positional Coach|link=]]',
        ['strategic coach'] = '[[File:Strategic coach icon blue.png|16px|Strategic Coach|link=]]',
        ['strategical coach'] = '[[File:Strategic coach icon blue.png|16px|Strategic Coach|link=]]',
        ['interim head coach'] = '[[File:Head coach icon blue.png|16px|Interim Head Coach|link=]]',
        ['interim coach'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Interim Coach"><i class="fad fa-user-tie"></i></abbr></span>',

        ['head analyst'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Head Analyst"><i class="fad fa-analytics"></i></abbr></span>',
        ['data analyst'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Data Analyst"><i class="fad fa-analytics"></i></abbr></span>',
        ['strategic analyst'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Strategic Analyst"><i class="fad fa-analytics"></i></abbr></span>',
        ['assistant analyst'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Assistant Analyst"><i class="fad fa-analytics"></i></abbr></span>',
        analyst = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Analyst"><i class="fad fa-analytics"></i></abbr></span>',
        ['general manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="General Manager">\'\'\'M\'\'\'</abbr></span>',
        manager = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Manager">\'\'\'M\'\'\'</abbr></span>',
        ['team manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Team Manager">\'\'\'M\'\'\'</abbr></span>',
        ['performance manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Performance Manager">\'\'\'M\'\'\'</abbr></span>',
        ['head manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Head Manager">\'\'\'M\'\'\'</abbr></span>',
        ['assistant manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Assistant Manager">\'\'\'M\'\'\'</abbr></span>',
        ['content creator'] = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Content Creator"><i class="fad fa-video"></i></abbr></span>',
        streamer = '<span class="elm-theme-dark-text" style="width:16px; display:inline-block; text-align:center"><abbr title="Streamer"><i class="fad fa-video"></i></abbr></span>',

        scout = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Scout">\'\'\'SC\'\'\'</abbr></span>',
        ['talent scout'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Talent Scout">\'\'\'SC\'\'\'</abbr></span>',
        supervisor = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Supervisor">\'\'\'SU\'\'\'</abbr></span>',
        leader = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Leader">\'\'\'L\'\'\'</abbr></span>',
        ['marketing manager'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Marketing Manager">\'\'\'M\'\'\'</abbr></span>',
        ['sign language translator'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Sign Language Translator">\'\'\'T\'\'\'</abbr></span>',
        ['skill acquisition specialist'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Skill Acquisition Specialist">\'\'\'SA\'\'\'</abbr></span>',
        staff = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Staff">\'\'\'ST\'\'\'</abbr></span>',
        ['chief operating officer'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Chief Operating Officer">\'\'\'ST\'\'\'</abbr></span>',
        sub = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Substitute">\'\'\'S\'\'\'</abbr></span>',
        substitute = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Substitute">\'\'\'S\'\'\'</abbr></span>',
        ['team director'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Team Director">\'\'\'D\'\'\'</abbr></span>',
        ['team representative'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Team Representative">\'\'\'R\'\'\'</abbr></span>',
        ['technical director'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Technical Director">\'\'\'D\'\'\'</abbr></span>',
        director = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Team Director">\'\'\'D\'\'\'</abbr></span>',
        ['director of esports analytics'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Director of Esports Analytics">\'\'\'D\'\'\'</abbr></span>',
        ['technical assistant'] = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Technical Assistant">\'\'\'TA\'\'\'</abbr></span>',
        translator = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Translator">\'\'\'TR\'\'\'</abbr></span>',
        coordinator = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Coordinator">\'\'\'CO\'\'\'</abbr></span>',
        ambassador = '<span style="width:16px; display:inline-block; text-align:center"><abbr title="Ambassador">\'\'\'A\'\'\'</abbr></span>'
    }
} --[[@as TransferData]]
