---
-- @Liquipedia
-- page=Module:Region/Ept/Data
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

--[[
Data for ESL Pro Tour regions. Used by wikis with ESL Pro Tour tournaments,
namely starcraft2, warcraft, and counterstrike.

Regions are defined in the ESL Pro Tour rulebook.
EPT Rulebook for StarCraft 2:
https://www.intelextrememasters.com/season-15/katowice/wp-content/uploads/2020/12/IEMRulebook.pdf
EOT Rulebook for CS:GO:
https://cdn.eslgaming.com/misc/media/lo/ESL%20Pro%20Tour%20-%20CSGO%20General%20Rules.pdf
]]
return {
	{
		name = 'Others',
		countries = {
			'Non-representing',
		},
	},
	{
		name = 'Americas',
		countries = {
			'Anguilla',
			'Antarctica',
			'Antigua and Barbuda',
			'Argentina',
			'Aruba',
			'Bahamas',
			'Barbados',
			'Belize',
			'Bermuda',
			'Bolivia',
			'Bonaire, Sint Eustatius and Saba',
			'Bouvet Island',
			'Brazil',
			'Canada',
			'Cayman Islands',
			'Chile',
			'Colombia',
			'Costa Rica',
			'Cuba',
			'Curaçao',
			'Dominica',
			'Dominican Republic',
			'Ecuador',
			'El Salvador',
			'Falkland Islands',
			'French Southern Territories',
			'Grenada',
			'Guadeloupe',
			'Guatemala',
			'Guyana',
			'Haiti',
			'Heard Island and McDonald Islands',
			'Honduras',
			'Jamaica',
			'Martinique',
			'Mexico',
			'Montserrat',
			'Nicaragua',
			'Panama',
			'Paraguay',
			'Peru',
			'Puerto Rico',
			'Saint Barthélemy',
			'Saint Kitts and Nevis',
			'Saint Lucia',
			'Saint Martin (French part)',
			'Saint Pierre and Miquelon',
			'Saint Vincent and the Grenadines',
			'Sint Maarten (Dutch part)',
			'South Georgia and the South Sandwich Islands',
			'Suriname',
			'Trinidad and Tobago',
			'Turks and Caicos Islands',
			'United States Minor Outlying Islands', -- TODO
			'United States',
			'Uruguay',
			'Venezuela',
			'Virgin Islands (British)',
			'Virgin Islands (U.S.)',
		},
	},
	{
		name = 'Asia & Australia',
		countries = {
			'Afghanistan',
			'American Samoa',
			'Australia',
			'Bahrain',
			'Bangladesh',
			'Bhutan',
			'British Indian Ocean Territory',
			'Brunei',
			'Cambodia',
			'China',
			'Christmas Island',
			'Cocos (Keeling) Islands',
			'Cook Islands',
			'Federated States of Micronesia',
			'Fiji',
			'French Polynesia',
			'Guam',
			'Hong Kong',
			'India',
			'Indonesia',
			'Iran',
			'Iraq',
			'Japan',
			'Jordan',
			'Kiribati',
			'Kuwait',
			'Kyrgyzstan',
			'Laos',
			'Lebanon',
			'Macau',
			'Malaysia',
			'Maldives',
			'Marshall Islands',
			'Mongolia',
			'Myanmar',
			'Nauru',
			'Nepal',
			'New Caledonia',
			'New Zealand',
			'Niue',
			'Norfolk Island',
			'North Korea',
			'Northern Mariana Islands',
			'Oman',
			'Pakistan',
			'Palau',
			'Palestine',
			'Papua New Guinea',
			'Philippines',
			'Pitcairn',
			'Qatar',
			'Samoa',
			'Saudi Arabia',
			'Singapore',
			'Solomon Islands',
			'South Korea',
			'Sri Lanka',
			'Syria',
			'Taiwan',
			'Tajikistan',
			'Thailand',
			'Timor-Leste',
			'Tokelau',
			'Tonga',
			'Turkmenistan',
			'Tuvalu',
			'United Arab Emirates',
			'Vanuatu',
			'Vietnam',
			'Wallis and Futuna',
		},
	},
	{
		name = 'Europe & Africa',
		countries = {
			'Albania',
			'Algeria',
			'Andorra',
			'Angola',
			'Armenia',
			'Ascension Island',
			'Austria',
			'Azerbaijan',
			'Belarus',
			'Belgium',
			'Benin',
			'Bosnia and Herzegovina',
			'Botswana',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Cabo Verde',
			'Cameroon',
			'Central African Republic',
			'Chad',
			'Comoros',
			'Congo',
			'Croatia',
			'Cyprus',
			'Czechia',
			'Côte d\'Ivoire',
			'Democratic Republic of the Congo',
			'Denmark',
			'Djibouti',
			'Egypt',
			'England',
			'Equatorial Guinea',
			'Eritrea',
			'Estonia',
			'Eswatini',
			'Ethiopia',
			'Faroe Islands',
			'Finland',
			'France',
			'French Guiana',
			'Gabon',
			'Gambia',
			'Georgia',
			'Germany',
			'Ghana',
			'Gibraltar',
			'Greece',
			'Greenland',
			'Guernsey',
			'Guinea',
			'Guinea-Bissau',
			'Hungary',
			'Iceland',
			'Ireland',
			'Isle of Man',
			'Israel',
			'Italy',
			'Jersey',
			'Kazakhstan',
			'Kenya',
			'Kosovo',
			'Latvia',
			'Lesotho',
			'Liberia',
			'Libya',
			'Liechtenstein',
			'Lithuania',
			'Luxembourg',
			'Madagascar',
			'Malawi',
			'Mali',
			'Malta',
			'Mauritania',
			'Mauritius',
			'Mayotte',
			'Moldova',
			'Monaco',
			'Montenegro',
			'Morocco',
			'Mozambique',
			'Namibia',
			'Netherlands',
			'Niger',
			'Nigeria',
			'North Macedonia',
			'Northern Ireland',
			'Norway',
			'Poland',
			'Portugal',
			'Romania',
			'Russia',
			'Rwanda',
			'Réunion',
			'Saint Helena',
			'San Marino',
			'Sao Tome and Principe',
			'Scotland',
			'Senegal',
			'Serbia',
			'Seychelles',
			'Sierra Leone',
			'Slovakia',
			'Slovenia',
			'Somalia',
			'South Africa',
			'South Sudan',
			'Spain',
			'Sudan',
			'Svalbard and Jan Mayen',
			'Sweden',
			'Switzerland',
			'Tanzania',
			'Togo',
			'Tristan da Cunha',
			'Tunisia',
			'Turkey',
			'Uganda',
			'Ukraine',
			'United Kingdom',
			'Uzbekistan',
			'Vatican City',
			'Wales',
			'Western Sahara',
			'Yemen',
			'Zambia',
			'Zimbabwe',
			'Åland Islands',
		},
	},
}
