---
-- @Liquipedia
-- page=Module:TestAssets/Standings
--
-- Please see https://github.com/Liquipedia/Lua-Modules to contribute
--

-- luacheck: ignore
return {
	standingsindex = 0,
	title = '',
	type = 'league',
	matches = {},
	roundCount = 9,
	hasdraw = false,
	hasovertime = true,
	finished = false,
	enddate = '2022-10-31',
	entries = {
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 7,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 3,
			['roundindex'] = 1,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 3,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 4,
				['w'] = 7,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 3,
			['roundindex'] = 1,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 3,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 4,
				['w'] = 7,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 3,
			['roundindex'] = 1,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 5,
				['w'] = 7,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 3,
			['roundindex'] = 1,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 6,
				['w'] = 8,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 2,
			['roundindex'] = 1,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 8,
				['w'] = 6,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 1,
			['roundindex'] = 1,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 7,
				['w'] = 5,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 0,
			['roundindex'] = 1,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -3,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 7,
				['w'] = 4,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 0,
			['roundindex'] = 1,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -3,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 7,
				['w'] = 4,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 0,
			['roundindex'] = 1,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 7,
				['w'] = 3,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 1,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 10,
				['w'] = 15,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 5,
			['roundindex'] = 2,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 10,
				['w'] = 15,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 5,
			['roundindex'] = 2,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'up',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 11,
				['w'] = 13,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 4,
			['roundindex'] = 2,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'up',
			['diff'] = 1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 12,
				['w'] = 13,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 4,
			['roundindex'] = 2,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'stay',
			['diff'] = 0,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 12,
				['w'] = 12,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 3,
			['roundindex'] = 2,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = 0,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 14,
				['w'] = 14,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 3,
			['roundindex'] = 2,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = 3,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 12,
				['w'] = 10,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 3,
			['roundindex'] = 2,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 14,
				['w'] = 12,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 2,
			['roundindex'] = 2,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 15,
				['w'] = 11,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 1,
			['roundindex'] = 2,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = -3,
			['currentstatus'] = 'stay',
			['diff'] = -5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 14,
				['w'] = 9,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 2,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 15,
				['w'] = 22,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 8,
			['roundindex'] = 3,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'up',
			['diff'] = 7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 16,
				['w'] = 23,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 7,
			['roundindex'] = 3,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'up',
			['diff'] = 1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 19,
				['w'] = 20,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 5,
			['roundindex'] = 3,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 0,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 20,
				['w'] = 20,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 5,
			['roundindex'] = 3,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = 0,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 18,
				['w'] = 18,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 4,
			['roundindex'] = 3,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'stay',
			['diff'] = -1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 21,
				['w'] = 20,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 4,
			['roundindex'] = 3,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = -1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 22,
				['w'] = 21,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -2,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 4,
			['roundindex'] = 3,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 20,
				['w'] = 18,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 4,
			['roundindex'] = 3,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 20,
				['w'] = 16,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 4,
			['roundindex'] = 3,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 21,
				['w'] = 14,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 3,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 20,
				['w'] = 30,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 10,
			['roundindex'] = 4,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 22,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 8,
			['roundindex'] = 4,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'up',
			['diff'] = 4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 22,
				['w'] = 26,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 8,
			['roundindex'] = 4,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 20,
				['w'] = 25,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 7,
			['roundindex'] = 4,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'stay',
			['diff'] = 1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 27,
				['w'] = 28,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 7,
			['roundindex'] = 4,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 3,
			['currentstatus'] = 'stay',
			['diff'] = -1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 24,
				['w'] = 23,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 7,
			['roundindex'] = 4,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = -4,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 26,
				['w'] = 22,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 5,
			['roundindex'] = 4,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 28,
				['w'] = 24,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 4,
			['roundindex'] = 4,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'stay',
			['diff'] = -7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 27,
				['w'] = 20,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 4,
			['roundindex'] = 4,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -9,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 28,
				['w'] = 19,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 4,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 24,
				['w'] = 34,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 11,
			['roundindex'] = 5,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'up',
			['diff'] = 8,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 24,
				['w'] = 32,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 10,
			['roundindex'] = 5,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 27,
				['w'] = 32,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 10,
			['roundindex'] = 5,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'up',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 29,
				['w'] = 34,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 10,
			['roundindex'] = 5,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'stay',
			['diff'] = -1,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 30,
				['w'] = 29,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 8,
			['roundindex'] = 5,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 32,
				['w'] = 30,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 8,
			['roundindex'] = 5,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = -2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 34,
				['w'] = 32,
			},
			['match'] = {
				['d'] = 0,
				['l'] = -1,
				['w'] = 1,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 7,
			['roundindex'] = 5,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'stay',
			['diff'] = -3,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 30,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 7,
			['roundindex'] = 5,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'stay',
			['diff'] = -7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 35,
				['w'] = 28,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 4,
			['roundindex'] = 5,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -13,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 35,
				['w'] = 22,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 5,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 12,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 29,
				['w'] = 41,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 4,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 14,
			['roundindex'] = 6,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 11,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 28,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 4,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 13,
			['roundindex'] = 6,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 32,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 13,
			['roundindex'] = 6,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 1,
			['currentstatus'] = 'up',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 34,
				['w'] = 36,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 11,
			['roundindex'] = 6,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = 2,
			['currentstatus'] = 'stay',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 34,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 10,
			['roundindex'] = 6,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = -2,
			['currentstatus'] = 'stay',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 36,
				['w'] = 38,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 10,
			['roundindex'] = 6,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = -1,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 39,
				['w'] = 35,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 8,
			['roundindex'] = 6,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 37,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 7,
			['roundindex'] = 6,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 42,
				['w'] = 32,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 4,
			['roundindex'] = 6,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['definitestatus'] = 'stay',
			['diff'] = -15,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 42,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 6,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 12,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 29,
				['w'] = 41,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 4,
			},
			['opponent'] = {
				['template'] = 'rogue 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Rogue',
			['participantdisplay'] = 'Rogue',
			['participantflag'] = '',
			['placement'] = 1,
			['points'] = 14,
			['roundindex'] = 7,
			['slotindex'] = 1,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 11,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 28,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 4,
			},
			['opponent'] = {
				['template'] = 'wolves esports',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'Wolves Esports',
			['participantdisplay'] = 'Wolves Esports',
			['participantflag'] = '',
			['placement'] = 2,
			['points'] = 13,
			['roundindex'] = 7,
			['slotindex'] = 2,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 7,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 32,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'team bds 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team BDS',
			['participantdisplay'] = 'Team BDS',
			['participantflag'] = '',
			['placement'] = 3,
			['points'] = 13,
			['roundindex'] = 7,
			['slotindex'] = 3,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'up',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 34,
				['w'] = 36,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 3,
				['w'] = 3,
			},
			['opponent'] = {
				['template'] = 'mnm gaming 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 1,
			},
			['participant'] = 'MNM Gaming',
			['participantdisplay'] = 'MNM Gaming',
			['participantflag'] = '',
			['placement'] = 4,
			['points'] = 11,
			['roundindex'] = 7,
			['slotindex'] = 4,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = 5,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 34,
				['w'] = 39,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'natus vincere 2021',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 1,
			},
			['participant'] = 'Natus Vincere',
			['participantdisplay'] = 'Natus Vincere',
			['participantflag'] = '',
			['placement'] = 5,
			['points'] = 10,
			['roundindex'] = 7,
			['slotindex'] = 5,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = 2,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 36,
				['w'] = 38,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'heroic',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Heroic',
			['participantdisplay'] = 'Heroic',
			['participantflag'] = '',
			['placement'] = 6,
			['points'] = 10,
			['roundindex'] = 7,
			['slotindex'] = 6,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -4,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 39,
				['w'] = 35,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'outsiders (eul)',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 2,
				['w'] = 0,
			},
			['participant'] = 'Outsiders (EUL)',
			['participantdisplay'] = 'Outsiders',
			['participantflag'] = '',
			['placement'] = 7,
			['points'] = 8,
			['roundindex'] = 7,
			['slotindex'] = 7,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 37,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 2,
			},
			['opponent'] = {
				['template'] = 'g2 esports 2019',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 1,
				['w'] = 0,
			},
			['participant'] = 'G2 Esports',
			['participantdisplay'] = 'G2 Esports',
			['participantflag'] = '',
			['placement'] = 8,
			['points'] = 7,
			['roundindex'] = 7,
			['slotindex'] = 8,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['diff'] = -10,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 42,
				['w'] = 32,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'team secret',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 2,
			},
			['participant'] = 'Team Secret',
			['participantdisplay'] = 'Team Secret',
			['participantflag'] = '',
			['placement'] = 9,
			['points'] = 4,
			['roundindex'] = 7,
			['slotindex'] = 9,
			['standingsindex'] = '0',
		},
		{
			['change'] = 0,
			['currentstatus'] = 'stay',
			['definitestatus'] = 'stay',
			['diff'] = -15,
			['extradata'] = {
			},
			['game'] = {
				['d'] = 0,
				['l'] = 42,
				['w'] = 27,
			},
			['match'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['opponent'] = {
				['template'] = 'tt9 esports 2022',
				['type'] = 'team',
			},
			['overtime'] = {
				['d'] = 0,
				['l'] = 0,
				['w'] = 0,
			},
			['participant'] = 'TT9 Esports',
			['participantdisplay'] = 'TT9 Esports',
			['participantflag'] = '',
			['placement'] = 10,
			['points'] = 0,
			['roundindex'] = 7,
			['slotindex'] = 10,
			['standingsindex'] = '0',
		},
	}
}
