local aliases = {
	bds = 'team bds',
	mousesports = 'mouz',
	skt = 't1',
	['sk telecom t1'] = 't1',
	['team exon'] = 'exon',
	tl = 'team liquid',
	tt9 = 'tt9 esports',
	wol = 'wolves esports'
}

local data = {
	-- historical ones
	exon = {
		['0000-01-01'] = 'exon jan 2020',
		['2020-02-12'] = 'exon feb 2020',
		['2020-03-10'] = 'exon march 2020',
	},
	['team bds'] = {
		['0000-01-01'] = 'bds esport old',
		['2019-09-01'] = 'team bds orig',
		['2021-12-17'] = 'team bds 2021',
	},
	mouz = {
		['0000-01-01'] = 'mousesports orig',
		['2016-06-01'] = 'mousesports 2016',
		['2021-10-14'] = 'mouz 2021',
	},
	['tt9 esports'] = {
		['0000-01-01'] = 'tt9 esports orig',
		['2021-03-31'] = 'tt9 esports 2021',
		['2022-09-01'] = 'tt9 esports 2022',
	},
	['t1'] = {
		['0000-01-01'] = 'sk telecom t1 orig',
		['2019-11-11'] = 't1 2019',
	},
	['team liquid'] = {
		['0000-01-01'] = 'team liquid orig',
		['2017-01-17'] = 'team liquid 2017',
		['2019-09-17'] = 'team liquid 2019',
		['2020-02-04'] = 'team liquid 2020',
		['2023-02-21'] = 'team liquid 2023',
		['2024-02-20'] = 'team liquid 2024',
	},
	['heroic'] = {
		['0000-01-01'] = 'heroic orig',
		['2023-01-26'] = 'heroic 2023',
		['2024-02-20'] = 'heroic 2024',
	},
	-- bds subtemplates
	['bds esport old'] = {
		bracketname = "BDS Esport",
		image = "BDS Esport 2019 allmode.png",
		imagedark = "BDS Esport 2019 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "BDS Esport",
		page = "BDS Esport",
		shortname = "BDS",
		templatename = "bds esport old",
	},
	['team bds orig'] = {
		bracketname = "Team BDS",
		image = "BDS Esport 2019.png",
		imagedark = "BDS Esport 2019.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team BDS",
		page = "Team BDS",
		shortname = "BDS",
		templatename = "team bds orig",
	},
	['team bds 2021'] = {
		bracketname = "Team BDS",
		image = "Team BDS 2021 allmode.png",
		imagedark = "Team BDS 2021 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team BDS",
		page = "Team BDS",
		shortname = "BDS",
		templatename = "team bds 2021",
	},
	-- exon subtemplates
	['exon jan 2020'] = {
		bracketname = "eXon",
		image = "",
		imagedark = "",
		legacyimage = "Exon logo std.png",
		legacyimagedark = "Exon logo std.png",
		name = "eXon",
		page = "eXon",
		shortname = "eXon",
		templatename = "exon jan 2020",
	},
	['exon feb 2020'] = {
		bracketname = "Team eXon",
		image = "",
		imagedark = "",
		legacyimage = "Exon feb 2020 logo std.png",
		legacyimagedark = "Exon feb 2020 logo std.png",
		name = "Team eXon",
		page = "Team eXon",
		shortname = "eXon",
		templatename = "exon feb 2020",
	},
	['exon march 2020'] = {
		bracketname = "Team eXoN",
		image = "",
		imagedark = "",
		legacyimage = "Exon feb 2020 logo std.png",
		legacyimagedark = "Exon feb 2020 logo std.png",
		name = "Team eXoN",
		page = "Team eXoN",
		shortname = "eXoN",
		templatename = "exon march 2020",
	},
	-- mouz subtemplates
	['mousesports orig'] = {
		bracketname = "mousesports",
		image = "Mousesports new.png",
		imagedark = "Mousesports new.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "mousesports",
		page = "mousesports",
		shortname = "mouz",
		templatename = "mousesports orig",
	},
	['mousesports 2016'] = {
		bracketname = "mousesports",
		image = "Mousesports 2016 allmodes.png",
		imagedark = "Mousesports 2016 allmodes.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "mousesports",
		page = "mousesports",
		shortname = "mouz",
		templatename = "mousesports 2016",
	},
	['mouz 2021'] = {
		bracketname = "MOUZ",
		image = "MOUZ allmode.png",
		imagedark = "MOUZ allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "MOUZ",
		page = "MOUZ",
		shortname = "MOUZ",
		templatename = "mouz 2021",
	},
	-- t1 subtemplates
	['sk telecom t1 orig'] = {
		bracketname = "SK Telecom T1",
		image = "SK Telecom T1 full allmode.png",
		imagedark = "SK Telecom T1 full allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "SK Telecom T1",
		page = "SK Telecom T1",
		shortname = "SKT",
		templatename = "sk telecom t1 orig",
	},
	['t1 2019'] = {
		bracketname = "T1",
		image = "T1 2019 allmode.png",
		imagedark = "T1 2019 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "T1",
		page = "T1",
		shortname = "T1",
		templatename = "t1 2019",
	},
	-- tl subtemplates
	['team liquid orig'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid lightmode.png",
		imagedark = "Team Liquid lightmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid orig",
	},
	['team liquid 2017'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid 2017 lightmode.png",
		imagedark = "Team Liquid 2017 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid 2017",
	},
	['team liquid 2019'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid 2019 lightmode.png",
		imagedark = "Team Liquid 2019 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid 2019",
	},
	['team liquid 2020'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid 2020 lightmode.png",
		imagedark = "Team Liquid 2020 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid 2020",
	},
	['team liquid 2023'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid 2023 lightmode.png",
		imagedark = "Team Liquid 2023 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid 2023",
	},
	['team liquid 2024'] = {
		bracketname = "Team Liquid",
		image = "Team Liquid 2024 lightmode.png",
		imagedark = "Team Liquid 2024 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Liquid",
		page = "Team Liquid",
		shortname = "Liquid",
		templatename = "team liquid 2024",
	},
	-- heroic subtemplates
	['heroic orig'] = {
		bracketname = "Heroic",
		image = "Heroic 2019 lightmode.png",
		imagedark = "Heroic 2019 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Heroic",
		page = "Heroic",
		shortname = "HERO",
		templatename = "heroic orig",
	},
	['heroic 2023'] = {
		bracketname = "Heroic",
		image = "Heroic 2023 allmode.png",
		imagedark = "Heroic 2023 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Heroic",
		page = "Heroic",
		shortname = "HERO",
		templatename = "heroic 2023",
	},
	['heroic 2024'] = {
		bracketname = "HEROIC",
		image = "Heroic 2023 allmode.png",
		imagedark = "Heroic 2023 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "HEROIC",
		page = "HEROIC",
		shortname = "HERO",
		templatename = "heroic 2024",
	},
	-- g2 subtemplate
	['g2 esports 2019'] = {
		bracketname = "G2 Esports",
		image = "G2 Esports 2019 lightmode.png",
		imagedark = "G2 Esports 2019 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "G2 Esports",
		page = "G2 Esports",
		shortname = "G2",
		templatename = "g2 esports 2019",
	},
	-- mnm subtemplate
	['mnm gaming 2021'] = {
		bracketname = "MNM Gaming",
		image = "MNM Gaming allmode.png",
		imagedark = "MNM Gaming allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "MNM Gaming",
		page = "MNM Gaming",
		shortname = "MNM",
		templatename = "mnm gaming 2021",
	},
	-- navi subtemplate
	['natus vincere 2021'] = {
		bracketname = "NAVI",
		image = "Natus Vincere 2021 lightmode.png",
		imagedark = "Natus Vincere 2021 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Natus Vincere",
		page = "Natus Vincere",
		shortname = "NAVI",
		templatename = "natus vincere 2021",
	},
	-- rogue subtemplate
	['rogue 2021'] = {
		bracketname = "Rogue",
		image = "Rogue 2021 lightmode.png",
		imagedark = "Rogue 2021 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Rogue",
		page = "Rogue",
		shortname = "RGE",
		templatename = "rogue 2021",
	},
	-- tt9 subtemplate
	['tt9 esports orig'] = {
		bracketname = "TT9 Esports",
		image = "TT9 Esports allmode.png",
		imagedark = "TT9 Esports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "TT9 Esports",
		page = "TT9 Esports",
		shortname = "TT9",
		templatename = "tt9 esports orig",
	},
	['tt9 esports 2021'] = {
		bracketname = "TT9 Esports",
		image = "TT9 Esports 2021 lightmode.png",
		imagedark = "TT9 Esports 2021 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "TT9 Esports",
		page = "TT9 Esports",
		shortname = "TT9",
		templatename = "tt9 esports 2021",
	},
	['tt9 esports 2022'] = {
		bracketname = "TT9 Esports",
		image = "TT9 Esports 2022 lightmode.png",
		imagedark = "TT9 Esports 2022 darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "TT9 Esports",
		page = "TT9 Esports",
		shortname = "TT9",
		templatename = "tt9 esports 2022",
	},
	-- non-historical TT
	['outsiders (eul)'] = {
		bracketname = "Outsiders",
		image = "Outsiders EUL 2022 allmode.png",
		imagedark = "Outsiders EUL 2022 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Outsiders",
		page = "Outsiders (EUL)",
		shortname = "OUT",
		templatename = "outsiders (eul)",
	},
	streamerzone = {
		bracketname = "Streamerzone",
		image = "Streamerzone lightmode.png",
		imagedark = "Streamerzone darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Streamerzone",
		page = "Streamerzone",
		shortname = "SZ",
		templatename = "streamerzone",
	},
	['team secret'] = {
		bracketname = "Team Secret",
		image = "Team Secret allmode.png",
		imagedark = "Team Secret allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Secret",
		page = "Team Secret",
		shortname = "Secret",
		templatename = "team secret",
	},
	['wolves esports'] = {
		bracketname = "Wolves Esports",
		image = "Wolves Esports allmode.png",
		imagedark = "Wolves Esports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Wolves Esports",
		page = "Wolves Esports",
		shortname = "WOL",
		templatename = "wolves esports",
	},
	-- Rainbow Six Siege teams from LPDB placement data
	['1upesport (german roster) orig'] = {
		bracketname = "1UPeSport",
		image = "1Upesport allmode.png",
		imagedark = "1Upesport allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "1UPeSport",
		page = "1UPeSport (German roster)",
		shortname = "1UP",
		templatename = "1upesport (german roster) orig",
	},
	['1upesport orig'] = {
		bracketname = "1UPeSport",
		image = "1Upesport allmode.png",
		imagedark = "1Upesport allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "1UPeSport",
		page = "1UPeSport",
		shortname = "1UP",
		templatename = "1upesport orig",
	},
	['1upesport/one 2018'] = {
		bracketname = "1UPeSport",
		image = "1UPeSport 2018 allmode.png",
		imagedark = "1UPeSport 2018 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "1UPeSport",
		page = "1UPeSport/One",
		shortname = "1UP",
		templatename = "1upesport/one 2018",
	},
	['1nfamy/united kingdom/one'] = {
		bracketname = "1nFamy",
		image = "1nFamy allmode.png",
		imagedark = "1nFamy allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "1nFamy",
		page = "1nFamy/United Kingdom/One",
		shortname = "1nF",
		templatename = "1nfamy/united kingdom",
	},
	['bad memes'] = {
		bracketname = "Bad Memes",
		image = "Rainbow Six Siege Logo lightmode.png",
		imagedark = "Rainbow Six Siege Logo Darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Bad Memes",
		page = "Bad Memes",
		shortname = "BM",
		templatename = "bad memes",
	},
	['bluejays sports'] = {
		bracketname = "BLUEJAYS Sports",
		image = "BLUEJAYS 2015 allmode.png",
		imagedark = "BLUEJAYS 2015 allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "BLUEJAYS Sports",
		page = "BLUEJAYS Sports",
		shortname = "BJ",
		templatename = "bluejays sports",
	},
	['botsofharris'] = {
		bracketname = "BotsofHarris",
		image = "Rainbow Six Siege Logo lightmode.png",
		imagedark = "Rainbow Six Siege Logo Darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "BotsofHarris",
		page = "BotsofHarris",
		shortname = "BoH",
		templatename = "botsofharris",
	},
	['buteo esports orig'] = {
		bracketname = "BUTEO eSports",
		image = "BUTEO eSports allmode.png",
		imagedark = "BUTEO eSports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "BUTEO eSports",
		page = "BUTEO eSports",
		shortname = "BUT",
		templatename = "buteo esports orig",
	},
	['comeback'] = {
		bracketname = "ComeBack",
		image = "ComeBack allmode.png",
		imagedark = "ComeBack allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "ComeBack",
		page = "ComeBack",
		shortname = "CB",
		templatename = "comeback",
	},
	['deus esport'] = {
		bracketname = "Deus Esport",
		image = "DEUS Esport lightmode.png",
		imagedark = "DEUS Esport darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Deus Esport",
		page = "Deus Esport",
		shortname = "DEUS",
		templatename = "deus esport",
	},
	['ewave esports orig'] = {
		bracketname = "EWAVE eSports",
		image = "EWave eSports allmode.png",
		imagedark = "EWave eSports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "eWAVE eSports",
		page = "EWAVE eSports",
		shortname = "EW",
		templatename = "ewave esports orig",
	},
	['mechanix esports'] = {
		bracketname = "Mechanix eSports",
		image = "Rainbow Six Siege Logo lightmode.png",
		imagedark = "Rainbow Six Siege Logo Darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Mechanix eSports",
		page = "Mechanix eSports",
		shortname = "MX",
		templatename = "mechanix esports",
	},
	['mysterious monkeys'] = {
		bracketname = "Mysterious Monkeys",
		image = "Mysterious Monkeys allmode.png",
		imagedark = "Mysterious Monkeys allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Mysterious Monkeys",
		page = "Mysterious Monkeys",
		shortname = "MM",
		templatename = "mysterious monkeys",
	},
	['myrisk gaming e.v.'] = {
		bracketname = "MyRisk Gaming e.V.",
		image = "myRisk Gaming e.V. allmode.png",
		imagedark = "myRisk Gaming e.V. allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "myRisk Gaming e.V.",
		page = "MyRisk Gaming e.V.",
		shortname = "MR",
		templatename = "myrisk gaming e.v.",
	},
	['ouroboros'] = {
		bracketname = "Ouroboros",
		image = "Ouroboros allmode.png",
		imagedark = "Ouroboros allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Ouroboros",
		page = "Ouroboros",
		shortname = "OUR",
		templatename = "ouroboros",
	},
	['quantum esports'] = {
		bracketname = "QuanTum eSports",
		image = "QuanTum eSports allmode.png",
		imagedark = "QuanTum eSports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "QuanTum eSports",
		page = "QuanTum eSports",
		shortname = "QT",
		templatename = "quantum esports",
	},
	['s1 esports'] = {
		bracketname = "S1 eSports",
		image = "S1 Esports allmode.png",
		imagedark = "S1 Esports allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "S1 eSports",
		page = "S1 eSports",
		shortname = "S1",
		templatename = "s1 esports",
	},
	['team synthax'] = {
		bracketname = "Team Synthax",
		image = "Rainbow Six Siege Logo lightmode.png",
		imagedark = "Rainbow Six Siege Logo Darkmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Team Synthax",
		page = "Team Synthax",
		shortname = "SYN",
		templatename = "team synthax",
	},
	['turtle esport'] = {
		bracketname = "Turtle eSport",
		image = "Turtle eSport allmode.png",
		imagedark = "Turtle eSport allmode.png",
		legacyimage = "",
		legacyimagedark = "",
		name = "Turtle eSport",
		page = "Turtle eSport",
		shortname = "TUR",
		templatename = "turtle esport",
	},
}

return {
	data = data,
	aliases = aliases,
}
