--- Triple Comment to Enable our LLS Plugin
describe('math', function()
	local MathUtil = require('Module:MathUtil')

	describe('isInteger', function()
		it('check numbers', function()
			assert.is_true(MathUtil.isInteger(0))
			assert.is_true(MathUtil.isInteger('5'))
			assert.is_true(MathUtil.isInteger(-125146145))
			assert.is_true(MathUtil.isInteger('142365709145'))
			assert.is_false(MathUtil.isInteger(math.pi))
			assert.is_false(MathUtil.isInteger('some nonsense'))
		end)

		it('check special values', function ()
			assert.is_false(MathUtil.isInteger(math.huge))
			assert.is_false(MathUtil.isInteger(-math.huge))
			assert.is_false(MathUtil.isInteger('nan'))
			assert.is_false(MathUtil.isInteger('-nan'))
		end)
	end)

	describe('i log 2', function()
		it('check', function()
			assert.are_equal(3, MathUtil.ilog2(8))
			assert.are_equal(4, MathUtil.ilog2(24))
		end)
	end)

	describe('sum', function()
		it('check', function()
			assert.are_equal(12, MathUtil.sum{3, 5, 4})
			assert.are_equal(0, MathUtil.sum{})
		end)
	end)

	describe('partial sum', function()
		it('check', function()
			assert.are_same({0, 3, 8, 12}, MathUtil.partialSums{3, 5, 4})
			assert.are_same({0}, MathUtil.partialSums{})
		end)
	end)

	describe('dot product', function()
		it('check', function()
			assert.are_equal(55, MathUtil.dotProduct({3, 2, 4}, {5, 6, 7}))
		end)
	end)

	describe('format rounded', function()
		it('check', function()
			assert.are_equal('12345.678', MathUtil.formatRounded{value = 12345.6777, precision = 3})
			assert.are_equal('121.83', MathUtil.formatRounded{value = 121.8265, precision = 2})
			assert.are_equal('0.33', MathUtil.formatRounded{value = 1 / 3, precision = 2})
		end)
	end)

	describe('format percentage', function()
		it('check', function()
			assert.are_equal('33.33%', MathUtil.formatPercentage(1 / 3, 2))
			assert.are_equal('66.67%', MathUtil.formatPercentage(2 / 3, 2))
		end)
	end)
end)
