--- Triple Comment to Enable our LLS Plugin
describe('Page Variable Namespace', function()
	local PVN = require('Module:PageVariableNamespace')

	describe('Global', function()
		it('check', function()
			local global = PVN()
			global:set('foo', 'bar')
			global:set('alice', 'bob')
			assert.are_equal(nil, global:get('baz'))
			assert.are_equal('bar', global:get('foo'))
			assert.are_equal('bob', global:get('alice'))
			global:delete('foo')
			assert.are_equal(nil, global:get('foo'))
			assert.are_equal('bob', global:get('alice'))
			global:delete('alice')
			assert.are_equal(nil, global:get('foo'))
			assert.are_equal(nil, global:get('alice'))
		end)
	end)

	describe('Namespace', function()
		it('check', function()
			local named = PVN('TestSpace')
			local global = PVN()
			named:set('foo', 'bar')
			named:set('alice', 'bob')
			assert.are_equal(nil, named:get('baz'))
			assert.are_equal('bar', named:get('foo'))
			assert.are_equal('bob', named:get('alice'))
			assert.are_equal(nil, global:get('foo'))
			named:delete('foo')
			assert.are_equal(nil, named:get('foo'))
			assert.are_equal('bob', named:get('alice'))
			named:delete('alice')
			assert.are_equal(nil, named:get('foo'))
			assert.are_equal(nil, named:get('alice'))
		end)
	end)
end)
