name: Unit Tests

on: [pull_request, workflow_dispatch]

jobs:
  test-lua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"

      - name: Setup ‘luarocks’ 
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install busted

      - name: Run test
        uses: lunarmodules/busted@v2.2.0
        with:
          args: --run=ci
