name: Protect page across wikis

on:
  workflow_dispatch:
    inputs:
      page:
        description: 'Page to protect (prefix with namespace!)'
        required: true

jobs:
  protect:
    if: github.ref_name == github.event.repository.default_branch
    name: Protect a given page across all wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python Dependency
        run: pip install requests

      - name: Page Protect
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          PAGE_TO_PROTECT: ${{ github.event.inputs.page }}
          PYTHONUNBUFFERED: 1
        run: python3 ./scripts/protect_page_across_wikis.py
